
let data = 
[
{ "categoryName":"Ability", "href":"/wiki/Ability_-_an_essential_subject" },
{ "categoryName":"Abode of Krishna", "href":"/wiki/Abode_of_Krishna_-_an_essential_subject" },
{ "categoryName":"Absolute Knowledge", "href":"/wiki/Absolute_Knowledge_-_an_essential_subject" },
{ "categoryName":"Absolute Truth", "href":"/wiki/Absolute_Truth_-_an_essential_subject" },
{ "categoryName":"Absorbed in Thought of Krishna", "href":"/wiki/Absorbed_in_Thought_of_Krishna_-_an_essential_subject" },
{ "categoryName":"Absorbing the Mind", "href":"/wiki/Absorbing_the_Mind_-_an_essential_subject" },
{ "categoryName":"Absorption", "href":"/wiki/Absorption_-_an_essential_subject" },
{ "categoryName":"Acarya", "href":"/wiki/Acarya_-_an_essential_subject" },
{ "categoryName":"Accepting a Spiritual Master", "href":"/wiki/Accepting_a_Spiritual_Master_-_an_essential_subject" },
{ "categoryName":"Accepting God", "href":"/wiki/Accepting_God_-_an_essential_subject" },
{ "categoryName":"Accepting Krishna", "href":"/wiki/Accepting_Krishna_-_an_essential_subject" },
{ "categoryName":"Accepting the Body as the Self", "href":"/wiki/Accepting_the_Body_as_the_Self_-_an_essential_subject" },
{ "categoryName":"Accumulating Money", "href":"/wiki/Accumulating_Money_-_an_essential_subject" },
{ "categoryName":"Accumulating Wealth", "href":"/wiki/Accumulating_Wealth_-_an_essential_subject" },
{ "categoryName":"Acquiring Knowledge", "href":"/wiki/Acquiring_Knowledge_-_an_essential_subject" },
{ "categoryName":"Acting in Krishna Consciousness", "href":"/wiki/Acting_in_Krishna_Consciousness_-_an_essential_subject" },
{ "categoryName":"Activities in Devotional Service", "href":"/wiki/Activities_in_Devotional_Service_-_an_essential_subject" },
{ "categoryName":"Adharma", "href":"/wiki/Adharma_-_an_essential_subject" },
{ "categoryName":"Advanced Devotees", "href":"/wiki/Advanced_Devotees_-_an_essential_subject" },
{ "categoryName":"Advanced in Knowledge", "href":"/wiki/Advanced_in_Knowledge_-_an_essential_subject" },
{ "categoryName":"Advanced in Krishna Consciousness", "href":"/wiki/Advanced_in_Krishna_Consciousness_-_an_essential_subject" },
{ "categoryName":"Advancement of Civilization", "href":"/wiki/Advancement_of_Civilization_-_an_essential_subject" },
{ "categoryName":"After Death", "href":"/wiki/After_Death_-_an_essential_subject" },
{ "categoryName":"Agitation", "href":"/wiki/Agitation_-_an_essential_subject" },
{ "categoryName":"Agriculture", "href":"/wiki/Agriculture_-_an_essential_subject" },
{ "categoryName":"Aham Brahmasmi", "href":"/wiki/Aham_Brahmasmi_-_an_essential_subject" },
{ "categoryName":"Aim of Life", "href":"/wiki/Aim_of_Life_-_an_essential_subject" },
{ "categoryName":"All pervasive", "href":"/wiki/All_pervasive_-_an_essential_subject" },
{ "categoryName":"All-powerful", "href":"/wiki/All-powerful_-_an_essential_subject" },
{ "categoryName":"Altar", "href":"/wiki/Altar_-_an_essential_subject" },
{ "categoryName":"Ambition", "href":"/wiki/Ambition_-_an_essential_subject" },
{ "categoryName":"Ananda (Bliss)", "href":"/wiki/Ananda_(Bliss)_-_an_essential_subject" },
{ "categoryName":"Anartha", "href":"/wiki/Anartha_-_an_essential_subject" },
{ "categoryName":"Anartha-nivrtti", "href":"/wiki/Anartha-nivrtti_-_an_essential_subject" },
{ "categoryName":"Anger", "href":"/wiki/Anger_-_an_essential_subject" },
{ "categoryName":"Animal Civilization", "href":"/wiki/Animal_Civilization_-_an_essential_subject" },
{ "categoryName":"Animal Life", "href":"/wiki/Animal_Life_-_an_essential_subject" },
{ "categoryName":"Animal Propensities", "href":"/wiki/Animal_Propensities_-_an_essential_subject" },
{ "categoryName":"Animal Sacrifice", "href":"/wiki/Animal_Sacrifice_-_an_essential_subject" },
{ "categoryName":"Animal Slaughter", "href":"/wiki/Animal_Slaughter_-_an_essential_subject" },
{ "categoryName":"Animal Society", "href":"/wiki/Animal_Society_-_an_essential_subject" },
{ "categoryName":"Animalistic", "href":"/wiki/Animalistic_-_an_essential_subject" },
{ "categoryName":"Antimaterial", "href":"/wiki/Antimaterial_-_an_essential_subject" },
{ "categoryName":"Anxiety", "href":"/wiki/Anxiety_-_an_essential_subject" },
{ "categoryName":"Appreciation", "href":"/wiki/Appreciation_-_an_essential_subject" },
{ "categoryName":"Approaching a Spiritual Master", "href":"/wiki/Approaching_a_Spiritual_Master_-_an_essential_subject" },
{ "categoryName":"Approaching Krishna", "href":"/wiki/Approaching_Krishna_-_an_essential_subject" },
{ "categoryName":"Arati", "href":"/wiki/Arati_-_an_essential_subject" },
{ "categoryName":"Aryan", "href":"/wiki/Aryan_-_an_essential_subject" },
{ "categoryName":"Asrama", "href":"/wiki/Asrama_-_an_essential_subject" },
{ "categoryName":"Assets", "href":"/wiki/Assets_-_an_essential_subject" },
{ "categoryName":"Association of Devotees", "href":"/wiki/Association_of_Devotees_-_an_essential_subject" },
{ "categoryName":"Association of Nondevotees", "href":"/wiki/Association_of_Nondevotees_-_an_essential_subject" },
{ "categoryName":"Association of Pure Devotees", "href":"/wiki/Association_of_Pure_Devotees_-_an_essential_subject" },
{ "categoryName":"At the Time of Death", "href":"/wiki/At_the_Time_of_Death_-_an_essential_subject" },
{ "categoryName":"Athato Brahma Jijnasa", "href":"/wiki/Athato_Brahma_Jijnasa_-_an_essential_subject" },
{ "categoryName":"Atheism", "href":"/wiki/Atheism_-_an_essential_subject" },
{ "categoryName":"Atma", "href":"/wiki/Atma_-_an_essential_subject" },
{ "categoryName":"Atonement", "href":"/wiki/Atonement_-_an_essential_subject" },
{ "categoryName":"Attachment for Krishna", "href":"/wiki/Attachment_for_Krishna_-_an_essential_subject" },
{ "categoryName":"Attachment for Women", "href":"/wiki/Attachment_for_Women_-_an_essential_subject" },
{ "categoryName":"Attaining Perfection", "href":"/wiki/Attaining_Perfection_-_an_essential_subject" },
{ "categoryName":"Attention", "href":"/wiki/Attention_-_an_essential_subject" },
{ "categoryName":"Auspiciousness", "href":"/wiki/Auspiciousness_-_an_essential_subject" },
{ "categoryName":"Austerity", "href":"/wiki/Austerity_-_an_essential_subject" },
{ "categoryName":"Authoritative Scriptures", "href":"/wiki/Authoritative_Scriptures_-_an_essential_subject" },
{ "categoryName":"Authoritative Sources", "href":"/wiki/Authoritative_Sources_-_an_essential_subject" },
{ "categoryName":"Authority of the Vedas", "href":"/wiki/Authority_of_the_Vedas_-_an_essential_subject" },
{ "categoryName":"Avatara", "href":"/wiki/Avatara_-_an_essential_subject" },
{ "categoryName":"Avidya", "href":"/wiki/Avidya_-_an_essential_subject" },
{ "categoryName":"Awareness", "href":"/wiki/Awareness_-_an_essential_subject" },
{ "categoryName":"Basic Principles", "href":"/wiki/Basic_Principles_-_an_essential_subject" },
{ "categoryName":"Battle of Kuruksetra", "href":"/wiki/Battle_of_Kuruksetra_-_an_essential_subject" },
{ "categoryName":"Becoming a Brahmana", "href":"/wiki/Becoming_a_Brahmana_-_an_essential_subject" },
{ "categoryName":"Becoming a Spiritual Master", "href":"/wiki/Becoming_a_Spiritual_Master_-_an_essential_subject" },
{ "categoryName":"Becoming God", "href":"/wiki/Becoming_God_-_an_essential_subject" },
{ "categoryName":"Becoming God Conscious", "href":"/wiki/Becoming_God_Conscious_-_an_essential_subject" },
{ "categoryName":"Becoming Happy", "href":"/wiki/Becoming_Happy_-_an_essential_subject" },
{ "categoryName":"Becoming Krishna Conscious", "href":"/wiki/Becoming_Krishna_Conscious_-_an_essential_subject" },
{ "categoryName":"Benediction", "href":"/wiki/Benediction_-_an_essential_subject" },
{ "categoryName":"Beneficial", "href":"/wiki/Beneficial_-_an_essential_subject" },
{ "categoryName":"Benefits", "href":"/wiki/Benefits_-_an_essential_subject" },
{ "categoryName":"Benevolent", "href":"/wiki/Benevolent_-_an_essential_subject" },
{ "categoryName":"Bewilderment", "href":"/wiki/Bewilderment_-_an_essential_subject" },
{ "categoryName":"Bhagavad-gita Says", "href":"/wiki/Bhagavad-gita_Says_-_an_essential_subject" },
{ "categoryName":"Bhagavan", "href":"/wiki/Bhagavan_-_an_essential_subject" },
{ "categoryName":"Bhagavata-dharma", "href":"/wiki/Bhagavata-dharma_-_an_essential_subject" },
{ "categoryName":"Bhakti", "href":"/wiki/Bhakti_-_an_essential_subject" },
{ "categoryName":"Bhakti-yoga", "href":"/wiki/Bhakti-yoga_-_an_essential_subject" },
{ "categoryName":"Bharata-varsa", "href":"/wiki/Bharata-varsa_-_an_essential_subject" },
{ "categoryName":"Bhava", "href":"/wiki/Bhava_-_an_essential_subject" },
{ "categoryName":"Bible", "href":"/wiki/Bible_-_an_essential_subject" },
{ "categoryName":"Birth after Birth", "href":"/wiki/Birth_after_Birth_-_an_essential_subject" },
{ "categoryName":"Birth and Death", "href":"/wiki/Birth_and_Death_-_an_essential_subject" },
{ "categoryName":"Birth, Death, Old Age and Disease", "href":"/wiki/Birth,_Death,_Old_Age_and_Disease_-_an_essential_subject" },
{ "categoryName":"Blasphemy", "href":"/wiki/Blasphemy_-_an_essential_subject" },
{ "categoryName":"Blessings", "href":"/wiki/Blessings_-_an_essential_subject" },
{ "categoryName":"Bliss", "href":"/wiki/Bliss_-_an_essential_subject" },
{ "categoryName":"Blissful Life", "href":"/wiki/Blissful_Life_-_an_essential_subject" },
{ "categoryName":"Bodily Concept of Life", "href":"/wiki/Bodily_Concept_of_Life_-_an_essential_subject" },
{ "categoryName":"Bodily Consciousness", "href":"/wiki/Bodily_Consciousness_-_an_essential_subject" },
{ "categoryName":"Bodily Necessities", "href":"/wiki/Bodily_Necessities_-_an_essential_subject" },
{ "categoryName":"Body and Mind", "href":"/wiki/Body_and_Mind_-_an_essential_subject" },
{ "categoryName":"Body and Soul", "href":"/wiki/Body_and_Soul_-_an_essential_subject" },
{ "categoryName":"Body of The Lord", "href":"/wiki/Body_of_The_Lord_-_an_essential_subject" },
{ "categoryName":"Bona Fide Spiritual Master", "href":"/wiki/Bona_Fide_Spiritual_Master_-_an_essential_subject" },
{ "categoryName":"Brahma-bhuta", "href":"/wiki/Brahma-bhuta_-_an_essential_subject" },
{ "categoryName":"Brahmacari", "href":"/wiki/Brahmacari_-_an_essential_subject" },
{ "categoryName":"Caitanya Mahaprabhu's Movement", "href":"/wiki/Caitanya_Mahaprabhu%27s_Movement_-_an_essential_subject" },
{ "categoryName":"Caitya-guru - the Spiritual Master Within", "href":"/wiki/Caitya-guru_-_the_Spiritual_Master_Within_-_an_essential_subject" },
{ "categoryName":"Celibacy", "href":"/wiki/Celibacy_-_an_essential_subject" },
{ "categoryName":"Chanting Hare Krishna", "href":"/wiki/Chanting_Hare_Krishna_-_an_essential_subject" },
{ "categoryName":"Charm", "href":"/wiki/Charm_-_an_essential_subject" },
{ "categoryName":"Cheating", "href":"/wiki/Cheating_-_an_essential_subject" },
{ "categoryName":"Cheating Propensity", "href":"/wiki/Cheating_Propensity_-_an_essential_subject" },
{ "categoryName":"Cognizant", "href":"/wiki/Cognizant_-_an_essential_subject" },
{ "categoryName":"Committing Mistakes", "href":"/wiki/Committing_Mistakes_-_an_essential_subject" },
{ "categoryName":"Common Sense", "href":"/wiki/Common_Sense_-_an_essential_subject" },
{ "categoryName":"Compassion", "href":"/wiki/Compassion_-_an_essential_subject" },
{ "categoryName":"Complete Knowledge", "href":"/wiki/Complete_Knowledge_-_an_essential_subject" },
{ "categoryName":"Compromise", "href":"/wiki/Compromise_-_an_essential_subject" },
{ "categoryName":"Concentrating the Mind", "href":"/wiki/Concentrating_the_Mind_-_an_essential_subject" },
{ "categoryName":"Conchshell", "href":"/wiki/Conchshell_-_an_essential_subject" },
{ "categoryName":"Conditioned Living Entities", "href":"/wiki/Conditioned_Living_Entities_-_an_essential_subject" },
{ "categoryName":"Conditioned Souls", "href":"/wiki/Conditioned_Souls_-_an_essential_subject" },
{ "categoryName":"Conditioned State", "href":"/wiki/Conditioned_State_-_an_essential_subject" },
{ "categoryName":"Confidential", "href":"/wiki/Confidential_-_an_essential_subject" },
{ "categoryName":"Confusion", "href":"/wiki/Confusion_-_an_essential_subject" },
{ "categoryName":"Connection", "href":"/wiki/Connection_-_an_essential_subject" },
{ "categoryName":"Contamination", "href":"/wiki/Contamination_-_an_essential_subject" },
{ "categoryName":"Controlling Deities", "href":"/wiki/Controlling_Deities_-_an_essential_subject" },
{ "categoryName":"Controlling the Mind", "href":"/wiki/Controlling_the_Mind_-_an_essential_subject" },
{ "categoryName":"Controlling the Senses", "href":"/wiki/Controlling_the_Senses_-_an_essential_subject" },
{ "categoryName":"Conviction", "href":"/wiki/Conviction_-_an_essential_subject" },
{ "categoryName":"Cooperating with the Krishna Consciousness Movement", "href":"/wiki/Cooperating_with_the_Krishna_Consciousness_Movement_-_an_essential_subject" },
{ "categoryName":"Cooperation", "href":"/wiki/Cooperation_-_an_essential_subject" },
{ "categoryName":"Corruption", "href":"/wiki/Corruption_-_an_essential_subject" },
{ "categoryName":"Cosmic Manifestation", "href":"/wiki/Cosmic_Manifestation_-_an_essential_subject" },
{ "categoryName":"Craziness", "href":"/wiki/Craziness_-_an_essential_subject" },
{ "categoryName":"Cruelty", "href":"/wiki/Cruelty_-_an_essential_subject" },
{ "categoryName":"Cultivating Krishna Consciousness", "href":"/wiki/Cultivating_Krishna_Consciousness_-_an_essential_subject" },
{ "categoryName":"Culture", "href":"/wiki/Culture_-_an_essential_subject" },
{ "categoryName":"Culture of Knowledge", "href":"/wiki/Culture_of_Knowledge_-_an_essential_subject" },
{ "categoryName":"Curses", "href":"/wiki/Curses_-_an_essential_subject" },
{ "categoryName":"Cycle of Birth and Death", "href":"/wiki/Cycle_of_Birth_and_Death_-_an_essential_subject" },
{ "categoryName":"Danger", "href":"/wiki/Danger_-_an_essential_subject" },
{ "categoryName":"Dead Bodies", "href":"/wiki/Dead_Bodies_-_an_essential_subject" },
{ "categoryName":"Death", "href":"/wiki/Death_-_an_essential_subject" },
{ "categoryName":"Death Means...", "href":"/wiki/Death_Means..._-_an_essential_subject" },
{ "categoryName":"Dedication", "href":"/wiki/Dedication_-_an_essential_subject" },
{ "categoryName":"Degradation", "href":"/wiki/Degradation_-_an_essential_subject" },
{ "categoryName":"Deity Worship", "href":"/wiki/Deity_Worship_-_an_essential_subject" },
{ "categoryName":"Delusion", "href":"/wiki/Delusion_-_an_essential_subject" },
{ "categoryName":"Demigod Worship", "href":"/wiki/Demigod_Worship_-_an_essential_subject" },
{ "categoryName":"Democracy", "href":"/wiki/Democracy_-_an_essential_subject" },
{ "categoryName":"Demoniac", "href":"/wiki/Demoniac_-_an_essential_subject" },
{ "categoryName":"Demons", "href":"/wiki/Demons_-_an_essential_subject" },
{ "categoryName":"Depending on Krishna", "href":"/wiki/Depending_on_Krishna_-_an_essential_subject" },
{ "categoryName":"Depression", "href":"/wiki/Depression_-_an_essential_subject" },
{ "categoryName":"Desireless", "href":"/wiki/Desireless_-_an_essential_subject" },
{ "categoryName":"Destiny", "href":"/wiki/Destiny_-_an_essential_subject" },
{ "categoryName":"Destruction", "href":"/wiki/Destruction_-_an_essential_subject" },
{ "categoryName":"Detachment", "href":"/wiki/Detachment_-_an_essential_subject" },
{ "categoryName":"Deterioration", "href":"/wiki/Deterioration_-_an_essential_subject" },
{ "categoryName":"Determination", "href":"/wiki/Determination_-_an_essential_subject" },
{ "categoryName":"Devastation", "href":"/wiki/Devastation_-_an_essential_subject" },
{ "categoryName":"Developing Krishna Consciousness", "href":"/wiki/Developing_Krishna_Consciousness_-_an_essential_subject" },
{ "categoryName":"Deviations", "href":"/wiki/Deviations_-_an_essential_subject" },
{ "categoryName":"Devotees Are Always...- an essential subject", "href":"/wiki/Devotees_Are_Always...-_an_essential_subject" },
{ "categoryName":"Devotees Are Not...- an essential subject", "href":"/wiki/Devotees_Are_Not...-_an_essential_subject" },
{ "categoryName":"Devotees Are...- an essential subject", "href":"/wiki/Devotees_Are...-_an_essential_subject" },
{ "categoryName":"Devotees Can...- an essential subject", "href":"/wiki/Devotees_Can...-_an_essential_subject" },
{ "categoryName":"Devotees Cannot...- an essential subject", "href":"/wiki/Devotees_Cannot...-_an_essential_subject" },
{ "categoryName":"Devotees Do Not...", "href":"/wiki/Devotees_Do_Not..._-_an_essential_subject" },
{ "categoryName":"Devotees Go Back to Godhead", "href":"/wiki/Devotees_Go_Back_to_Godhead_-_an_essential_subject" },
{ "categoryName":"Devotees Know...- an essential subject", "href":"/wiki/Devotees_Know...-_an_essential_subject" },
{ "categoryName":"Devotees Never...", "href":"/wiki/Devotees_Never..._-_an_essential_subject" },
{ "categoryName":"Devotees of Lord Caitanya", "href":"/wiki/Devotees_of_Lord_Caitanya_-_an_essential_subject" },
{ "categoryName":"Devotees of Lord Krishna", "href":"/wiki/Devotees_of_Lord_Krishna_-_an_essential_subject" },
{ "categoryName":"Devotees of the Lord", "href":"/wiki/Devotees_of_the_Lord_-_an_essential_subject" },
{ "categoryName":"Devotees Should Not...", "href":"/wiki/Devotees_Should_Not..._-_an_essential_subject" },
{ "categoryName":"Devotees Should...", "href":"/wiki/Devotees_Should..._-_an_essential_subject" },
{ "categoryName":"Devotees Sometimes...- an essential subject", "href":"/wiki/Devotees_Sometimes...-_an_essential_subject" },
{ "categoryName":"Devotees' Compassion", "href":"/wiki/Devotees%27_Compassion_-_an_essential_subject" },
{ "categoryName":"Devotion", "href":"/wiki/Devotion_-_an_essential_subject" },
{ "categoryName":"Devotional Ambition", "href":"/wiki/Devotional_Ambition_-_an_essential_subject" },
{ "categoryName":"Devotional Anger", "href":"/wiki/Devotional_Anger_-_an_essential_subject" },
{ "categoryName":"Devotional Anxiety", "href":"/wiki/Devotional_Anxiety_-_an_essential_subject" },
{ "categoryName":"Devotional Attachment", "href":"/wiki/Devotional_Attachment_-_an_essential_subject" },
{ "categoryName":"Devotional Service", "href":"/wiki/Devotional_Service_-_an_essential_subject" },
{ "categoryName":"Devotional Service to Krishna", "href":"/wiki/Devotional_Service_to_Krishna_-_an_essential_subject" },
{ "categoryName":"Dharma", "href":"/wiki/Dharma_-_an_essential_subject" },
{ "categoryName":"Dirty Things Within Our Heart", "href":"/wiki/Dirty_Things_Within_Our_Heart_-_an_essential_subject" },
{ "categoryName":"Disagreement", "href":"/wiki/Disagreement_-_an_essential_subject" },
{ "categoryName":"Disciplic Succession", "href":"/wiki/Disciplic_Succession_-_an_essential_subject" },
{ "categoryName":"Disclosure", "href":"/wiki/Disclosure_-_an_essential_subject" },
{ "categoryName":"Discrepancy", "href":"/wiki/Discrepancy_-_an_essential_subject" },
{ "categoryName":"Discrimination", "href":"/wiki/Discrimination_-_an_essential_subject" },
{ "categoryName":"Dishonesty", "href":"/wiki/Dishonesty_-_an_essential_subject" },
{ "categoryName":"Disobedience", "href":"/wiki/Disobedience_-_an_essential_subject" },
{ "categoryName":"Disrespectful", "href":"/wiki/Disrespectful_-_an_essential_subject" },
{ "categoryName":"Dissatisfaction", "href":"/wiki/Dissatisfaction_-_an_essential_subject" },
{ "categoryName":"Distress", "href":"/wiki/Distress_-_an_essential_subject" },
{ "categoryName":"Disturbances", "href":"/wiki/Disturbances_-_an_essential_subject" },
{ "categoryName":"Divisions of Human Society", "href":"/wiki/Divisions_of_Human_Society_-_an_essential_subject" },
{ "categoryName":"Divorce", "href":"/wiki/Divorce_-_an_essential_subject" },
{ "categoryName":"Doubt", "href":"/wiki/Doubt_-_an_essential_subject" },
{ "categoryName":"Dress of a Sannyasi", "href":"/wiki/Dress_of_a_Sannyasi_-_an_essential_subject" },
{ "categoryName":"Duality", "href":"/wiki/Duality_-_an_essential_subject" },
{ "categoryName":"Duplicity", "href":"/wiki/Duplicity_-_an_essential_subject" },
{ "categoryName":"Earning Money", "href":"/wiki/Earning_Money_-_an_essential_subject" },
{ "categoryName":"Eating, Sleeping, Mating and Defending", "href":"/wiki/Eating,_Sleeping,_Mating_and_Defending_-_an_essential_subject" },
{ "categoryName":"Economic Development", "href":"/wiki/Economic_Development_-_an_essential_subject" },
{ "categoryName":"Economic Problems", "href":"/wiki/Economic_Problems_-_an_essential_subject" },
{ "categoryName":"Ecstatic Love", "href":"/wiki/Ecstatic_Love_-_an_essential_subject" },
{ "categoryName":"Ecstatic Love For Krishna", "href":"/wiki/Ecstatic_Love_For_Krishna_-_an_essential_subject" },
{ "categoryName":"Ekadasi", "href":"/wiki/Ekadasi_-_an_essential_subject" },
{ "categoryName":"Embarrassment", "href":"/wiki/Embarrassment_-_an_essential_subject" },
{ "categoryName":"Embodied Souls", "href":"/wiki/Embodied_Souls_-_an_essential_subject" },
{ "categoryName":"Embryo", "href":"/wiki/Embryo_-_an_essential_subject" },
{ "categoryName":"Emotions", "href":"/wiki/Emotions_-_an_essential_subject" },
{ "categoryName":"Empowerment", "href":"/wiki/Empowerment_-_an_essential_subject" },
{ "categoryName":"Encagement", "href":"/wiki/Encagement_-_an_essential_subject" },
{ "categoryName":"Encouragement", "href":"/wiki/Encouragement_-_an_essential_subject" },
{ "categoryName":"Energies of the Lord", "href":"/wiki/Energies_of_the_Lord_-_an_essential_subject" },
{ "categoryName":"Engaging in Devotional Service", "href":"/wiki/Engaging_in_Devotional_Service_-_an_essential_subject" },
{ "categoryName":"Engaging in the Service of the Lord", "href":"/wiki/Engaging_in_the_Service_of_the_Lord_-_an_essential_subject" },
{ "categoryName":"Enjoying Life", "href":"/wiki/Enjoying_Life_-_an_essential_subject" },
{ "categoryName":"Enjoying Sex Life", "href":"/wiki/Enjoying_Sex_Life_-_an_essential_subject" },
{ "categoryName":"Entering into the Kingdom of God", "href":"/wiki/Entering_into_the_Kingdom_of_God_-_an_essential_subject" },
{ "categoryName":"Enthusiasm", "href":"/wiki/Enthusiasm_-_an_essential_subject" },
{ "categoryName":"Envious of God", "href":"/wiki/Envious_of_God_-_an_essential_subject" },
{ "categoryName":"Envy", "href":"/wiki/Envy_-_an_essential_subject" },
{ "categoryName":"Equal Rights", "href":"/wiki/Equal_Rights_-_an_essential_subject" },
{ "categoryName":"Eternal Existence", "href":"/wiki/Eternal_Existence_-_an_essential_subject" },
{ "categoryName":"Eternal Life", "href":"/wiki/Eternal_Life_-_an_essential_subject" },
{ "categoryName":"Eternal Relationships", "href":"/wiki/Eternal_Relationships_-_an_essential_subject" },
{ "categoryName":"Eternal Time", "href":"/wiki/Eternal_Time_-_an_essential_subject" },
{ "categoryName":"Everything Belongs to God", "href":"/wiki/Everything_Belongs_to_God_-_an_essential_subject" },
{ "categoryName":"Everything Belongs to Krishna", "href":"/wiki/Everything_Belongs_to_Krishna_-_an_essential_subject" },
{ "categoryName":"Executing Devotional Service", "href":"/wiki/Executing_Devotional_Service_-_an_essential_subject" },
{ "categoryName":"Executive Heads of States", "href":"/wiki/Executive_Heads_of_States_-_an_essential_subject" },
{ "categoryName":"Extraordinary", "href":"/wiki/Extraordinary_-_an_essential_subject" },
{ "categoryName":"Faith", "href":"/wiki/Faith_-_an_essential_subject" },
{ "categoryName":"Faith in God", "href":"/wiki/Faith_in_God_-_an_essential_subject" },
{ "categoryName":"Faith in Krishna", "href":"/wiki/Faith_in_Krishna_-_an_essential_subject" },
{ "categoryName":"Fall Down", "href":"/wiki/Fall_Down_-_an_essential_subject" },
{ "categoryName":"False Ego", "href":"/wiki/False_Ego_-_an_essential_subject" },
{ "categoryName":"False Identification", "href":"/wiki/False_Identification_-_an_essential_subject" },
{ "categoryName":"Family Attachment", "href":"/wiki/Family_Attachment_-_an_essential_subject" },
{ "categoryName":"Fear", "href":"/wiki/Fear_-_an_essential_subject" },
{ "categoryName":"Fearfulness", "href":"/wiki/Fearfulness_-_an_essential_subject" },
{ "categoryName":"Fearlessness", "href":"/wiki/Fearlessness_-_an_essential_subject" },
{ "categoryName":"Firm Faith", "href":"/wiki/Firm_Faith_-_an_essential_subject" },
{ "categoryName":"First-class Men", "href":"/wiki/First-class_Men_-_an_essential_subject" },
{ "categoryName":"Following in the Footsteps", "href":"/wiki/Following_in_the_Footsteps_-_an_essential_subject" },
{ "categoryName":"Fools and Rascals", "href":"/wiki/Fools_and_Rascals_-_an_essential_subject" },
{ "categoryName":"Forgetful Living Entities", "href":"/wiki/Forgetful_Living_Entities_-_an_essential_subject" },
{ "categoryName":"Forgetful Souls", "href":"/wiki/Forgetful_Souls_-_an_essential_subject" },
{ "categoryName":"Forgiveness", "href":"/wiki/Forgiveness_-_an_essential_subject" },
{ "categoryName":"Free from Anxiety", "href":"/wiki/Free_from_Anxiety_-_an_essential_subject" },
{ "categoryName":"Free from Bondage", "href":"/wiki/Free_from_Bondage_-_an_essential_subject" },
{ "categoryName":"Free from Contamination", "href":"/wiki/Free_from_Contamination_-_an_essential_subject" },
{ "categoryName":"Free from Designation", "href":"/wiki/Free_from_Designation_-_an_essential_subject" },
{ "categoryName":"Free from Material Desire", "href":"/wiki/Free_from_Material_Desire_-_an_essential_subject" },
{ "categoryName":"Free from Miseries", "href":"/wiki/Free_from_Miseries_-_an_essential_subject" },
{ "categoryName":"Free from Reaction", "href":"/wiki/Free_from_Reaction_-_an_essential_subject" },
{ "categoryName":"Friendship", "href":"/wiki/Friendship_-_an_essential_subject" },
{ "categoryName":"Fruitive Activities", "href":"/wiki/Fruitive_Activities_-_an_essential_subject" },
{ "categoryName":"Fruitive Workers", "href":"/wiki/Fruitive_Workers_-_an_essential_subject" },
{ "categoryName":"Frustration", "href":"/wiki/Frustration_-_an_essential_subject" },
{ "categoryName":"Full Krishna Consciousness", "href":"/wiki/Full_Krishna_Consciousness_-_an_essential_subject" },
{ "categoryName":"Fully Surrendering (atma-nivedanam)", "href":"/wiki/Fully_Surrendering_(atma-nivedanam)_-_an_essential_subject" },
{ "categoryName":"Gains", "href":"/wiki/Gains_-_an_essential_subject" },
{ "categoryName":"Gambling", "href":"/wiki/Gambling_-_an_essential_subject" },
{ "categoryName":"Ganges", "href":"/wiki/Ganges_-_an_essential_subject" },
{ "categoryName":"Gaudiya Vaisnava", "href":"/wiki/Gaudiya_Vaisnava_-_an_essential_subject" },
{ "categoryName":"Gayatri", "href":"/wiki/Gayatri_-_an_essential_subject" },
{ "categoryName":"Go Back to Home, Back to Godhead", "href":"/wiki/Go_Back_to_Home,_Back_to_Godhead_-_an_essential_subject" },
{ "categoryName":"God Conscious", "href":"/wiki/God_Conscious_-_an_essential_subject" },
{ "categoryName":"God Consciousness", "href":"/wiki/God_Consciousness_-_an_essential_subject" },
{ "categoryName":"God Give Us Our Daily Bread", "href":"/wiki/God_Give_Us_Our_Daily_Bread_-_an_essential_subject" },
{ "categoryName":"God is Dead", "href":"/wiki/God_is_Dead_-_an_essential_subject" },
{ "categoryName":"God is Everywhere", "href":"/wiki/God_is_Everywhere_-_an_essential_subject" },
{ "categoryName":"God is God", "href":"/wiki/God_is_God_-_an_essential_subject" },
{ "categoryName":"God is Great", "href":"/wiki/God_is_Great_-_an_essential_subject" },
{ "categoryName":"God is Not so Cheap", "href":"/wiki/God_is_Not_so_Cheap_-_an_essential_subject" },
{ "categoryName":"God is One", "href":"/wiki/God_is_One_-_an_essential_subject" },
{ "categoryName":"God Realization", "href":"/wiki/God_Realization_-_an_essential_subject" },
{ "categoryName":"God Says", "href":"/wiki/God_Says_-_an_essential_subject" },
{ "categoryName":"God's Compassion", "href":"/wiki/God%27s_Compassion_-_an_essential_subject" },
{ "categoryName":"God's Creation", "href":"/wiki/God%27s_Creation_-_an_essential_subject" },
{ "categoryName":"God's Killing", "href":"/wiki/God%27s_Killing_-_an_essential_subject" },
{ "categoryName":"Godless Civilization", "href":"/wiki/Godless_Civilization_-_an_essential_subject" },
{ "categoryName":"Godlessness", "href":"/wiki/Godlessness_-_an_essential_subject" },
{ "categoryName":"Godly Qualities", "href":"/wiki/Godly_Qualities_-_an_essential_subject" },
{ "categoryName":"Goloka Vrndavana - Krishnaloka", "href":"/wiki/Goloka_Vrndavana_-_Krishnaloka_-_an_essential_subject" },
{ "categoryName":"Good Qualities", "href":"/wiki/Good_Qualities_-_an_essential_subject" },
{ "categoryName":"Gosvami", "href":"/wiki/Gosvami_-_an_essential_subject" },
{ "categoryName":"Govardhana", "href":"/wiki/Govardhana_-_an_essential_subject" },
{ "categoryName":"Gratefulness", "href":"/wiki/Gratefulness_-_an_essential_subject" },
{ "categoryName":"Great Acaryas", "href":"/wiki/Great_Acaryas_-_an_essential_subject" },
{ "categoryName":"Great Offenses", "href":"/wiki/Great_Offenses_-_an_essential_subject" },
{ "categoryName":"Great Service", "href":"/wiki/Great_Service_-_an_essential_subject" },
{ "categoryName":"Greatest Authority", "href":"/wiki/Greatest_Authority_-_an_essential_subject" },
{ "categoryName":"Greatest Danger", "href":"/wiki/Greatest_Danger_-_an_essential_subject" },
{ "categoryName":"Greatest of All", "href":"/wiki/Greatest_of_All_-_an_essential_subject" },
{ "categoryName":"Greatest Service", "href":"/wiki/Greatest_Service_-_an_essential_subject" },
{ "categoryName":"Grhastha", "href":"/wiki/Grhastha_-_an_essential_subject" },
{ "categoryName":"Guru-parampara- an essential subject", "href":"/wiki/Guru-parampara-_an_essential_subject" },
{ "categoryName":"Happiness", "href":"/wiki/Happiness_-_an_essential_subject" },
{ "categoryName":"Happiness and Distress", "href":"/wiki/Happiness_and_Distress_-_an_essential_subject" },
{ "categoryName":"Hatha-yoga", "href":"/wiki/Hatha-yoga_-_an_essential_subject" },
{ "categoryName":"Hearing and Chanting", "href":"/wiki/Hearing_and_Chanting_-_an_essential_subject" },
{ "categoryName":"Hearing Srimad-Bhagavatam", "href":"/wiki/Hearing_Srimad-Bhagavatam_-_an_essential_subject" },
{ "categoryName":"Hellish Condition", "href":"/wiki/Hellish_Condition_-_an_essential_subject" },
{ "categoryName":"Hellish Life", "href":"/wiki/Hellish_Life_-_an_essential_subject" },
{ "categoryName":"Highest Benefits", "href":"/wiki/Highest_Benefits_-_an_essential_subject" },
{ "categoryName":"Holy Names of God", "href":"/wiki/Holy_Names_of_God_-_an_essential_subject" },
{ "categoryName":"Honesty", "href":"/wiki/Honesty_-_an_essential_subject" },
{ "categoryName":"Human Civilization", "href":"/wiki/Human_Civilization_-_an_essential_subject" },
{ "categoryName":"Human Form of Life", "href":"/wiki/Human_Form_of_Life_-_an_essential_subject" },
{ "categoryName":"Human Life is meant for", "href":"/wiki/Human_Life_is_meant_for_-_an_essential_subject" },
{ "categoryName":"Humanity", "href":"/wiki/Humanity_-_an_essential_subject" },
{ "categoryName":"Humble and Meek", "href":"/wiki/Humble_and_Meek_-_an_essential_subject" },
{ "categoryName":"Humility", "href":"/wiki/Humility_-_an_essential_subject" },
{ "categoryName":"Hypocrisy", "href":"/wiki/Hypocrisy_-_an_essential_subject" },
{ "categoryName":"I Am God", "href":"/wiki/I_Am_God_-_an_essential_subject" },
{ "categoryName":"I Am Not This Body", "href":"/wiki/I_Am_Not_This_Body_-_an_essential_subject" },
{ "categoryName":"I Am Spirit Soul", "href":"/wiki/I_Am_Spirit_Soul_-_an_essential_subject" },
{ "categoryName":"Identification With The Body", "href":"/wiki/Identification_With_The_Body_-_an_essential_subject" },
{ "categoryName":"Idol Worship", "href":"/wiki/Idol_Worship_-_an_essential_subject" },
{ "categoryName":"Illicit Sex Life", "href":"/wiki/Illicit_Sex_Life_-_an_essential_subject" },
{ "categoryName":"Impediment", "href":"/wiki/Impediment_-_an_essential_subject" },
{ "categoryName":"Incarnations of God", "href":"/wiki/Incarnations_of_God_-_an_essential_subject" },
{ "categoryName":"Inferior Energy - Material Matter", "href":"/wiki/Inferior_Energy_-_Material_Matter_-_an_essential_subject" },
{ "categoryName":"Influence of Time", "href":"/wiki/Influence_of_Time_-_an_essential_subject" },
{ "categoryName":"Instructions of the Spiritual Master", "href":"/wiki/Instructions_of_the_Spiritual_Master_-_an_essential_subject" },
{ "categoryName":"Intoxication", "href":"/wiki/Intoxication_-_an_essential_subject" },
{ "categoryName":"Isvara", "href":"/wiki/Isvara_-_an_essential_subject" },
{ "categoryName":"Jagannatha Puri", "href":"/wiki/Jagannatha_Puri_-_an_essential_subject" },
{ "categoryName":"Jealousy", "href":"/wiki/Jealousy_-_an_essential_subject" },
{ "categoryName":"Jiva", "href":"/wiki/Jiva_-_an_essential_subject" },
{ "categoryName":"Jnana", "href":"/wiki/Jnana_-_an_essential_subject" },
{ "categoryName":"Jnana-kanda", "href":"/wiki/Jnana-kanda_-_an_essential_subject" },
{ "categoryName":"Jnani", "href":"/wiki/Jnani_-_an_essential_subject" },
{ "categoryName":"Kama", "href":"/wiki/Kama_-_an_essential_subject" },
{ "categoryName":"Karma", "href":"/wiki/Karma_-_an_essential_subject" },
{ "categoryName":"Karma-kanda", "href":"/wiki/Karma-kanda_-_an_essential_subject" },
{ "categoryName":"Karma-yoga", "href":"/wiki/Karma-yoga_-_an_essential_subject" },
{ "categoryName":"Killing Animals", "href":"/wiki/Killing_Animals_-_an_essential_subject" },
{ "categoryName":"Kingdom of God", "href":"/wiki/Kingdom_of_God_-_an_essential_subject" },
{ "categoryName":"Kirtana", "href":"/wiki/Kirtana_-_an_essential_subject" },
{ "categoryName":"Knowing God", "href":"/wiki/Knowing_God_-_an_essential_subject" },
{ "categoryName":"Knowledge of God", "href":"/wiki/Knowledge_of_God_-_an_essential_subject" },
{ "categoryName":"Knowledge of Krishna", "href":"/wiki/Knowledge_of_Krishna_-_an_essential_subject" },
{ "categoryName":"Krishna and the Gopis", "href":"/wiki/Krishna_and_the_Gopis_-_an_essential_subject" },
{ "categoryName":"Krishna Conscious Education", "href":"/wiki/Krishna_Conscious_Education_-_an_essential_subject" },
{ "categoryName":"Krishna Conscious Persons", "href":"/wiki/Krishna_Conscious_Persons_-_an_essential_subject" },
{ "categoryName":"Krishna Consciousness Means", "href":"/wiki/Krishna_Consciousness_Means_-_an_essential_subject" },
{ "categoryName":"Krishna Consciousness Movement is a Spiritual Movement", "href":"/wiki/Krishna_Consciousness_Movement_is_a_Spiritual_Movement_-_an_essential_subject" },
{ "categoryName":"Krishna Consciousness Movement is an Educational Movement", "href":"/wiki/Krishna_Consciousness_Movement_is_an_Educational_Movement_-_an_essential_subject" },
{ "categoryName":"Krishna Consciousness Movement is Not a Sectarian Movement", "href":"/wiki/Krishna_Consciousness_Movement_is_Not_a_Sectarian_Movement_-_an_essential_subject" },
{ "categoryName":"Krishna Consciousness Movement Is Not...", "href":"/wiki/Krishna_Consciousness_Movement_Is_Not..._-_an_essential_subject" },
{ "categoryName":"Krishna Consciousness Movement is Saving the World", "href":"/wiki/Krishna_Consciousness_Movement_is_Saving_the_World_-_an_essential_subject" },
{ "categoryName":"Krishna Consciousness Movement is Teaching...", "href":"/wiki/Krishna_Consciousness_Movement_is_Teaching..._-_an_essential_subject" },
{ "categoryName":"Krishna Consciousness Movement Is...", "href":"/wiki/Krishna_Consciousness_Movement_Is..._-_an_essential_subject" },
{ "categoryName":"Krishna Consciousness Movement Means", "href":"/wiki/Krishna_Consciousness_Movement_Means_-_an_essential_subject" },
{ "categoryName":"Krishna is Everywhere", "href":"/wiki/Krishna_is_Everywhere_-_an_essential_subject" },
{ "categoryName":"Krishna is God", "href":"/wiki/Krishna_is_God_-_an_essential_subject" },
{ "categoryName":"Krishna is So Kind", "href":"/wiki/Krishna_is_So_Kind_-_an_essential_subject" },
{ "categoryName":"Krishna's Beauty", "href":"/wiki/Krishna%27s_Beauty_-_an_essential_subject" },
{ "categoryName":"Krishna's Body", "href":"/wiki/Krishna%27s_Body_-_an_essential_subject" },
{ "categoryName":"Krishna's Disappearance", "href":"/wiki/Krishna%27s_Disappearance_-_an_essential_subject" },
{ "categoryName":"Krishna's Face", "href":"/wiki/Krishna%27s_Face_-_an_essential_subject" },
{ "categoryName":"Krishna, the Friend of All", "href":"/wiki/Krishna,_the_Friend_of_All_-_an_essential_subject" },
{ "categoryName":"Krishna-prema", "href":"/wiki/Krishna-prema_-_an_essential_subject" },
{ "categoryName":"Ksatriyas", "href":"/wiki/Ksatriyas_-_an_essential_subject" },
{ "categoryName":"Ksetra-jna", "href":"/wiki/Ksetra-jna_-_an_essential_subject" },
{ "categoryName":"Laws of God", "href":"/wiki/Laws_of_God_-_an_essential_subject" },
{ "categoryName":"Leaders", "href":"/wiki/Leaders_-_an_essential_subject" },
{ "categoryName":"Leaving this Body", "href":"/wiki/Leaving_this_Body_-_an_essential_subject" },
{ "categoryName":"Liberated from", "href":"/wiki/Liberated_from_-_an_essential_subject" },
{ "categoryName":"Liberated Persons", "href":"/wiki/Liberated_Persons_-_an_essential_subject" },
{ "categoryName":"Liberated Souls", "href":"/wiki/Liberated_Souls_-_an_essential_subject" },
{ "categoryName":"Liberation", "href":"/wiki/Liberation_-_an_essential_subject" },
{ "categoryName":"Life after Death", "href":"/wiki/Life_after_Death_-_an_essential_subject" },
{ "categoryName":"Limited", "href":"/wiki/Limited_-_an_essential_subject" },
{ "categoryName":"Line of Disciplic Succession", "href":"/wiki/Line_of_Disciplic_Succession_-_an_essential_subject" },
{ "categoryName":"Lover of God", "href":"/wiki/Lover_of_God_-_an_essential_subject" },
{ "categoryName":"Loving Affairs", "href":"/wiki/Loving_Affairs_-_an_essential_subject" },
{ "categoryName":"Loving Devotional Service", "href":"/wiki/Loving_Devotional_Service_-_an_essential_subject" },
{ "categoryName":"Loving God", "href":"/wiki/Loving_God_-_an_essential_subject" },
{ "categoryName":"Loving Propensity", "href":"/wiki/Loving_Propensity_-_an_essential_subject" },
{ "categoryName":"Loving Service", "href":"/wiki/Loving_Service_-_an_essential_subject" },
{ "categoryName":"Madness", "href":"/wiki/Madness_-_an_essential_subject" },
{ "categoryName":"Maha-bhagavata", "href":"/wiki/Maha-bhagavata_-_an_essential_subject" },
{ "categoryName":"Maha-mantra", "href":"/wiki/Maha-mantra_-_an_essential_subject" },
{ "categoryName":"Mahajanas", "href":"/wiki/Mahajanas_-_an_essential_subject" },
{ "categoryName":"Mahat-tattva", "href":"/wiki/Mahat-tattva_-_an_essential_subject" },
{ "categoryName":"Management", "href":"/wiki/Management_-_an_essential_subject" },
{ "categoryName":"Mantra", "href":"/wiki/Mantra_-_an_essential_subject" },
{ "categoryName":"Manufacturing Ideas", "href":"/wiki/Manufacturing_Ideas_-_an_essential_subject" },
{ "categoryName":"Marginal Energy", "href":"/wiki/Marginal_Energy_-_an_essential_subject" },
{ "categoryName":"Marginal Potency", "href":"/wiki/Marginal_Potency_-_an_essential_subject" },
{ "categoryName":"Material Activities", "href":"/wiki/Material_Activities_-_an_essential_subject" },
{ "categoryName":"Material Advancement", "href":"/wiki/Material_Advancement_-_an_essential_subject" },
{ "categoryName":"Material Association", "href":"/wiki/Material_Association_-_an_essential_subject" },
{ "categoryName":"Material Atmosphere", "href":"/wiki/Material_Atmosphere_-_an_essential_subject" },
{ "categoryName":"Material Attachment", "href":"/wiki/Material_Attachment_-_an_essential_subject" },
{ "categoryName":"Material Benefits", "href":"/wiki/Material_Benefits_-_an_essential_subject" },
{ "categoryName":"Material Bodies", "href":"/wiki/Material_Bodies_-_an_essential_subject" },
{ "categoryName":"Material Body", "href":"/wiki/Material_Body_-_an_essential_subject" },
{ "categoryName":"Material Bondage", "href":"/wiki/Material_Bondage_-_an_essential_subject" },
{ "categoryName":"Material Civilization", "href":"/wiki/Material_Civilization_-_an_essential_subject" },
{ "categoryName":"Material Comforts", "href":"/wiki/Material_Comforts_-_an_essential_subject" },
{ "categoryName":"Material Conception", "href":"/wiki/Material_Conception_-_an_essential_subject" },
{ "categoryName":"Material Consciousness", "href":"/wiki/Material_Consciousness_-_an_essential_subject" },
{ "categoryName":"Material Contamination", "href":"/wiki/Material_Contamination_-_an_essential_subject" },
{ "categoryName":"Material Creation", "href":"/wiki/Material_Creation_-_an_essential_subject" },
{ "categoryName":"Material Desires", "href":"/wiki/Material_Desires_-_an_essential_subject" },
{ "categoryName":"Material Disease", "href":"/wiki/Material_Disease_-_an_essential_subject" },
{ "categoryName":"Material Energy", "href":"/wiki/Material_Energy_-_an_essential_subject" },
{ "categoryName":"Material Enjoyment", "href":"/wiki/Material_Enjoyment_-_an_essential_subject" },
{ "categoryName":"Material Entanglement", "href":"/wiki/Material_Entanglement_-_an_essential_subject" },
{ "categoryName":"Material Existence", "href":"/wiki/Material_Existence_-_an_essential_subject" },
{ "categoryName":"Material Form", "href":"/wiki/Material_Form_-_an_essential_subject" },
{ "categoryName":"Material Gains", "href":"/wiki/Material_Gains_-_an_essential_subject" },
{ "categoryName":"Material Happiness", "href":"/wiki/Material_Happiness_-_an_essential_subject" },
{ "categoryName":"Material Knowledge", "href":"/wiki/Material_Knowledge_-_an_essential_subject" },
{ "categoryName":"Material Life", "href":"/wiki/Material_Life_-_an_essential_subject" },
{ "categoryName":"Material Manifestation", "href":"/wiki/Material_Manifestation_-_an_essential_subject" },
{ "categoryName":"Material Miseries", "href":"/wiki/Material_Miseries_-_an_essential_subject" },
{ "categoryName":"Material Nature", "href":"/wiki/Material_Nature_-_an_essential_subject" },
{ "categoryName":"Material Opulence", "href":"/wiki/Material_Opulence_-_an_essential_subject" },
{ "categoryName":"Material Platform", "href":"/wiki/Material_Platform_-_an_essential_subject" },
{ "categoryName":"Material Possessions", "href":"/wiki/Material_Possessions_-_an_essential_subject" },
{ "categoryName":"Material Qualities", "href":"/wiki/Material_Qualities_-_an_essential_subject" },
{ "categoryName":"Material Science", "href":"/wiki/Material_Science_-_an_essential_subject" },
{ "categoryName":"Material Senses", "href":"/wiki/Material_Senses_-_an_essential_subject" },
{ "categoryName":"Material Universe", "href":"/wiki/Material_Universe_-_an_essential_subject" },
{ "categoryName":"Materialism", "href":"/wiki/Materialism_-_an_essential_subject" },
{ "categoryName":"Materialists", "href":"/wiki/Materialists_-_an_essential_subject" },
{ "categoryName":"Matter and Spirit", "href":"/wiki/Matter_and_Spirit_-_an_essential_subject" },
{ "categoryName":"Maya the Illusory Energy", "href":"/wiki/Maya_the_Illusory_Energy_-_an_essential_subject" },
{ "categoryName":"Mayavada Philosophy", "href":"/wiki/Mayavada_Philosophy_-_an_essential_subject" },
{ "categoryName":"Mayavadi Philosophers", "href":"/wiki/Mayavadi_Philosophers_-_an_essential_subject" },
{ "categoryName":"Mayavadi Sannyasis", "href":"/wiki/Mayavadi_Sannyasis_-_an_essential_subject" },
{ "categoryName":"Meat-eating", "href":"/wiki/Meat-eating_-_an_essential_subject" },
{ "categoryName":"Meditation", "href":"/wiki/Meditation_-_an_essential_subject" },
{ "categoryName":"Memory", "href":"/wiki/Memory_-_an_essential_subject" },
{ "categoryName":"Mental Concoction", "href":"/wiki/Mental_Concoction_-_an_essential_subject" },
{ "categoryName":"Mental Speculation", "href":"/wiki/Mental_Speculation_-_an_essential_subject" },
{ "categoryName":"Mental Speculators", "href":"/wiki/Mental_Speculators_-_an_essential_subject" },
{ "categoryName":"Mercantile Class - Vaisyas", "href":"/wiki/Mercantile_Class_-_Vaisyas_-_an_essential_subject" },
{ "categoryName":"Mercy", "href":"/wiki/Mercy_-_an_essential_subject" },
{ "categoryName":"Mercy of God", "href":"/wiki/Mercy_of_God_-_an_essential_subject" },
{ "categoryName":"Mercy of Guru", "href":"/wiki/Mercy_of_Guru_-_an_essential_subject" },
{ "categoryName":"Mind", "href":"/wiki/Mind_-_an_essential_subject" },
{ "categoryName":"Miscreants", "href":"/wiki/Miscreants_-_an_essential_subject" },
{ "categoryName":"Miserable Conditions", "href":"/wiki/Miserable_Conditions_-_an_essential_subject" },
{ "categoryName":"Miseries of Life", "href":"/wiki/Miseries_of_Life_-_an_essential_subject" },
{ "categoryName":"Misinterpretation", "href":"/wiki/Misinterpretation_-_an_essential_subject" },
{ "categoryName":"Mission of Caitanya Mahaprabhu", "href":"/wiki/Mission_of_Caitanya_Mahaprabhu_-_an_essential_subject" },
{ "categoryName":"Mission of Human Life", "href":"/wiki/Mission_of_Human_Life_-_an_essential_subject" },
{ "categoryName":"Mistakes", "href":"/wiki/Mistakes_-_an_essential_subject" },
{ "categoryName":"Misuse", "href":"/wiki/Misuse_-_an_essential_subject" },
{ "categoryName":"Mleccha", "href":"/wiki/Mleccha_-_an_essential_subject" },
{ "categoryName":"Mode of Goodness", "href":"/wiki/Mode_of_Goodness_-_an_essential_subject" },
{ "categoryName":"Mode of Ignorance", "href":"/wiki/Mode_of_Ignorance_-_an_essential_subject" },
{ "categoryName":"Mode of Passion", "href":"/wiki/Mode_of_Passion_-_an_essential_subject" },
{ "categoryName":"Modern Civilization", "href":"/wiki/Modern_Civilization_-_an_essential_subject" },
{ "categoryName":"Money- an essential subject", "href":"/wiki/Money-_an_essential_subject" },
{ "categoryName":"Mortality", "href":"/wiki/Mortality_-_an_essential_subject" },
{ "categoryName":"Mudha", "href":"/wiki/Mudha_-_an_essential_subject" },
{ "categoryName":"Mukti", "href":"/wiki/Mukti_-_an_essential_subject" },
{ "categoryName":"Mystery", "href":"/wiki/Mystery_-_an_essential_subject" },
{ "categoryName":"Naked", "href":"/wiki/Naked_-_an_essential_subject" },
{ "categoryName":"Nastiness", "href":"/wiki/Nastiness_-_an_essential_subject" },
{ "categoryName":"Negative", "href":"/wiki/Negative_-_an_essential_subject" },
{ "categoryName":"Neophyte devotee", "href":"/wiki/Neophyte_devotee_-_an_essential_subject" },
{ "categoryName":"Next Life", "href":"/wiki/Next_Life_-_an_essential_subject" },
{ "categoryName":"Nine Processes of Devotional Service", "href":"/wiki/Nine_Processes_of_Devotional_Service_-_an_essential_subject" },
{ "categoryName":"Nirvana", "href":"/wiki/Nirvana_-_an_essential_subject" },
{ "categoryName":"Nitya", "href":"/wiki/Nitya_-_an_essential_subject" },
{ "categoryName":"No Limit", "href":"/wiki/No_Limit_-_an_essential_subject" },
{ "categoryName":"Nondevotees", "href":"/wiki/Nondevotees_-_an_essential_subject" },
{ "categoryName":"Nonsense", "href":"/wiki/Nonsense_-_an_essential_subject" },
{ "categoryName":"Nonviolence", "href":"/wiki/Nonviolence_-_an_essential_subject" },
{ "categoryName":"Not Believing in God", "href":"/wiki/Not_Believing_in_God_-_an_essential_subject" },
{ "categoryName":"Not Envious", "href":"/wiki/Not_Envious_-_an_essential_subject" },
{ "categoryName":"Not Surrendered", "href":"/wiki/Not_Surrendered_-_an_essential_subject" },
{ "categoryName":"Occupational Duties", "href":"/wiki/Occupational_Duties_-_an_essential_subject" },
{ "categoryName":"Offering Garlands to the Lord", "href":"/wiki/Offering_Garlands_to_the_Lord_-_an_essential_subject" },
{ "categoryName":"Offering Prayers", "href":"/wiki/Offering_Prayers_-_an_essential_subject" },
{ "categoryName":"Old Age", "href":"/wiki/Old_Age_-_an_essential_subject" },
{ "categoryName":"Omkara", "href":"/wiki/Omkara_-_an_essential_subject" },
{ "categoryName":"One With God", "href":"/wiki/One_With_God_-_an_essential_subject" },
{ "categoryName":"Opulence", "href":"/wiki/Opulence_-_an_essential_subject" },
{ "categoryName":"Orders of Krishna", "href":"/wiki/Orders_of_Krishna_-_an_essential_subject" },
{ "categoryName":"Orders of the Spiritual Master", "href":"/wiki/Orders_of_the_Spiritual_Master_-_an_essential_subject" },
{ "categoryName":"Origin", "href":"/wiki/Origin_-_an_essential_subject" },
{ "categoryName":"Origin Of All", "href":"/wiki/Origin_Of_All_-_an_essential_subject" },
{ "categoryName":"Original Cause", "href":"/wiki/Original_Cause_-_an_essential_subject" },
{ "categoryName":"Original Consciousness", "href":"/wiki/Original_Consciousness_-_an_essential_subject" },
{ "categoryName":"Original Form of God", "href":"/wiki/Original_Form_of_God_-_an_essential_subject" },
{ "categoryName":"Original Personality of Godhead", "href":"/wiki/Original_Personality_of_Godhead_-_an_essential_subject" },
{ "categoryName":"Original Position", "href":"/wiki/Original_Position_-_an_essential_subject" },
{ "categoryName":"Original Source", "href":"/wiki/Original_Source_-_an_essential_subject" },
{ "categoryName":"Paramahamsa", "href":"/wiki/Paramahamsa_-_an_essential_subject" },
{ "categoryName":"Paramatma", "href":"/wiki/Paramatma_-_an_essential_subject" },
{ "categoryName":"Parampara", "href":"/wiki/Parampara_-_an_essential_subject" },
{ "categoryName":"Parampara System", "href":"/wiki/Parampara_System_-_an_essential_subject" },
{ "categoryName":"Part and Parcel of Krishna", "href":"/wiki/Part_and_Parcel_of_Krishna_-_an_essential_subject" },
{ "categoryName":"Passing Away", "href":"/wiki/Passing_Away_-_an_essential_subject" },
{ "categoryName":"Past Life", "href":"/wiki/Past_Life_-_an_essential_subject" },
{ "categoryName":"Past, Present and Future", "href":"/wiki/Past,_Present_and_Future_-_an_essential_subject" },
{ "categoryName":"Pastimes of the Lord", "href":"/wiki/Pastimes_of_the_Lord_-_an_essential_subject" },
{ "categoryName":"Path of Devotional Service", "href":"/wiki/Path_of_Devotional_Service_-_an_essential_subject" },
{ "categoryName":"Path of Liberation", "href":"/wiki/Path_of_Liberation_-_an_essential_subject" },
{ "categoryName":"Path of Self-realization", "href":"/wiki/Path_of_Self-realization_-_an_essential_subject" },
{ "categoryName":"Patience", "href":"/wiki/Patience_-_an_essential_subject" },
{ "categoryName":"Peace and Prosperity", "href":"/wiki/Peace_and_Prosperity_-_an_essential_subject" },
{ "categoryName":"Penance", "href":"/wiki/Penance_-_an_essential_subject" },
{ "categoryName":"Perfect Knowledge", "href":"/wiki/Perfect_Knowledge_-_an_essential_subject" },
{ "categoryName":"Perfection", "href":"/wiki/Perfection_-_an_essential_subject" },
{ "categoryName":"Perfection of Life", "href":"/wiki/Perfection_of_Life_-_an_essential_subject" },
{ "categoryName":"Performing Sacrifices", "href":"/wiki/Performing_Sacrifices_-_an_essential_subject" },
{ "categoryName":"Perpetuity", "href":"/wiki/Perpetuity_-_an_essential_subject" },
{ "categoryName":"Personal Benefits", "href":"/wiki/Personal_Benefits_-_an_essential_subject" },
{ "categoryName":"Personal Feature of the Lord", "href":"/wiki/Personal_Feature_of_the_Lord_-_an_essential_subject" },
{ "categoryName":"Pessimistic", "href":"/wiki/Pessimistic_-_an_essential_subject" },
{ "categoryName":"Philosophical Speculation", "href":"/wiki/Philosophical_Speculation_-_an_essential_subject" },
{ "categoryName":"Pious Activities", "href":"/wiki/Pious_Activities_-_an_essential_subject" },
{ "categoryName":"Places of Pilgrimage", "href":"/wiki/Places_of_Pilgrimage_-_an_essential_subject" },
{ "categoryName":"Planetary Systems", "href":"/wiki/Planetary_Systems_-_an_essential_subject" },
{ "categoryName":"Platform of Devotional Service", "href":"/wiki/Platform_of_Devotional_Service_-_an_essential_subject" },
{ "categoryName":"Pleasing Krishna", "href":"/wiki/Pleasing_Krishna_-_an_essential_subject" },
{ "categoryName":"Politicians", "href":"/wiki/Politicians_-_an_essential_subject" },
{ "categoryName":"Politics", "href":"/wiki/Politics_-_an_essential_subject" },
{ "categoryName":"Poor Fund of Knowledge", "href":"/wiki/Poor_Fund_of_Knowledge_-_an_essential_subject" },
{ "categoryName":"Positive", "href":"/wiki/Positive_-_an_essential_subject" },
{ "categoryName":"Pradhana", "href":"/wiki/Pradhana_-_an_essential_subject" },
{ "categoryName":"Prakrti", "href":"/wiki/Prakrti_-_an_essential_subject" },
{ "categoryName":"Prasadam", "href":"/wiki/Prasadam_-_an_essential_subject" },
{ "categoryName":"Preaching", "href":"/wiki/Preaching_-_an_essential_subject" },
{ "categoryName":"Preaching the Krishna Consciousness Movement", "href":"/wiki/Preaching_the_Krishna_Consciousness_Movement_-_an_essential_subject" },
{ "categoryName":"Predominating Deities", "href":"/wiki/Predominating_Deities_-_an_essential_subject" },
{ "categoryName":"Prema", "href":"/wiki/Prema_-_an_essential_subject" },
{ "categoryName":"Preparing for Our Next Life", "href":"/wiki/Preparing_for_Our_Next_Life_-_an_essential_subject" },
{ "categoryName":"Presence of Krishna", "href":"/wiki/Presence_of_Krishna_-_an_essential_subject" },
{ "categoryName":"Previous Acaryas", "href":"/wiki/Previous_Acaryas_-_an_essential_subject" },
{ "categoryName":"Previous births", "href":"/wiki/Previous_births_-_an_essential_subject" },
{ "categoryName":"Previous Lives", "href":"/wiki/Previous_Lives_-_an_essential_subject" },
{ "categoryName":"Pride", "href":"/wiki/Pride_-_an_essential_subject" },
{ "categoryName":"Principles of Devotional Service", "href":"/wiki/Principles_of_Devotional_Service_-_an_essential_subject" },
{ "categoryName":"Private", "href":"/wiki/Private_-_an_essential_subject" },
{ "categoryName":"Problems of Life", "href":"/wiki/Problems_of_Life_-_an_essential_subject" },
{ "categoryName":"Process of Bhakti", "href":"/wiki/Process_of_Bhakti_-_an_essential_subject" },
{ "categoryName":"Process of Devotional Service", "href":"/wiki/Process_of_Devotional_Service_-_an_essential_subject" },
{ "categoryName":"Producing Food Grains", "href":"/wiki/Producing_Food_Grains_-_an_essential_subject" },
{ "categoryName":"Propagating the Krishna Consciousness Movement", "href":"/wiki/Propagating_the_Krishna_Consciousness_Movement_-_an_essential_subject" },
{ "categoryName":"Prosperity", "href":"/wiki/Prosperity_-_an_essential_subject" },
{ "categoryName":"Protected by The Lord", "href":"/wiki/Protected_by_The_Lord_-_an_essential_subject" },
{ "categoryName":"Protecting Cows", "href":"/wiki/Protecting_Cows_-_an_essential_subject" },
{ "categoryName":"Protection of Women", "href":"/wiki/Protection_of_Women_-_an_essential_subject" },
{ "categoryName":"Psychology", "href":"/wiki/Psychology_-_an_essential_subject" },
{ "categoryName":"Puffed Up", "href":"/wiki/Puffed_Up_-_an_essential_subject" },
{ "categoryName":"Puranas", "href":"/wiki/Puranas_-_an_essential_subject" },
{ "categoryName":"Pure Consciousness", "href":"/wiki/Pure_Consciousness_-_an_essential_subject" },
{ "categoryName":"Pure Devotees of the Lord", "href":"/wiki/Pure_Devotees_of_the_Lord_-_an_essential_subject" },
{ "categoryName":"Pure Devotional Service", "href":"/wiki/Pure_Devotional_Service_-_an_essential_subject" },
{ "categoryName":"Pure Goodness", "href":"/wiki/Pure_Goodness_-_an_essential_subject" },
{ "categoryName":"Pure Love", "href":"/wiki/Pure_Love_-_an_essential_subject" },
{ "categoryName":"Pure Souls", "href":"/wiki/Pure_Souls_-_an_essential_subject" },
{ "categoryName":"Purification of the Heart", "href":"/wiki/Purification_of_the_Heart_-_an_essential_subject" },
{ "categoryName":"Purified Senses", "href":"/wiki/Purified_Senses_-_an_essential_subject" },
{ "categoryName":"Purity", "href":"/wiki/Purity_-_an_essential_subject" },
{ "categoryName":"Purpose of the Krishna Consciousness Movement", "href":"/wiki/Purpose_of_the_Krishna_Consciousness_Movement_-_an_essential_subject" },
{ "categoryName":"Purusa", "href":"/wiki/Purusa_-_an_essential_subject" },
{ "categoryName":"Pushing on the Krishna Consciousness Movement", "href":"/wiki/Pushing_on_the_Krishna_Consciousness_Movement_-_an_essential_subject" },
{ "categoryName":"Qualification", "href":"/wiki/Qualification_-_an_essential_subject" },
{ "categoryName":"Qualities of Krishna", "href":"/wiki/Qualities_of_Krishna_-_an_essential_subject" },
{ "categoryName":"Quality of Goodness", "href":"/wiki/Quality_of_Goodness_-_an_essential_subject" },
{ "categoryName":"Quitting this Body", "href":"/wiki/Quitting_this_Body_-_an_essential_subject" },
{ "categoryName":"Radha-Krishna Worship", "href":"/wiki/Radha-Krishna_Worship_-_an_essential_subject" },
{ "categoryName":"Ramayana", "href":"/wiki/Ramayana_-_an_essential_subject" },
{ "categoryName":"Rasa-lila", "href":"/wiki/Rasa-lila_-_an_essential_subject" },
{ "categoryName":"Rascal Civilization", "href":"/wiki/Rascal_Civilization_-_an_essential_subject" },
{ "categoryName":"Rascaldom", "href":"/wiki/Rascaldom_-_an_essential_subject" },
{ "categoryName":"Reaction", "href":"/wiki/Reaction_-_an_essential_subject" },
{ "categoryName":"Real Happiness", "href":"/wiki/Real_Happiness_-_an_essential_subject" },
{ "categoryName":"Real Identity", "href":"/wiki/Real_Identity_-_an_essential_subject" },
{ "categoryName":"Real Knowledge", "href":"/wiki/Real_Knowledge_-_an_essential_subject" },
{ "categoryName":"Real Love", "href":"/wiki/Real_Love_-_an_essential_subject" },
{ "categoryName":"Real Purpose", "href":"/wiki/Real_Purpose_-_an_essential_subject" },
{ "categoryName":"Real Religion", "href":"/wiki/Real_Religion_-_an_essential_subject" },
{ "categoryName":"Reality", "href":"/wiki/Reality_-_an_essential_subject" },
{ "categoryName":"Receiving Knowledge", "href":"/wiki/Receiving_Knowledge_-_an_essential_subject" },
{ "categoryName":"Regulative Principles", "href":"/wiki/Regulative_Principles_-_an_essential_subject" },
{ "categoryName":"Relationship with God", "href":"/wiki/Relationship_with_God_-_an_essential_subject" },
{ "categoryName":"Relationship with Krishna", "href":"/wiki/Relationship_with_Krishna_-_an_essential_subject" },
{ "categoryName":"Religion", "href":"/wiki/Religion_-_an_essential_subject" },
{ "categoryName":"Religious Principles", "href":"/wiki/Religious_Principles_-_an_essential_subject" },
{ "categoryName":"Remedies", "href":"/wiki/Remedies_-_an_essential_subject" },
{ "categoryName":"Remembering Krishna", "href":"/wiki/Remembering_Krishna_-_an_essential_subject" },
{ "categoryName":"Rendering Devotional Service", "href":"/wiki/Rendering_Devotional_Service_-_an_essential_subject" },
{ "categoryName":"Rendering Service", "href":"/wiki/Rendering_Service_-_an_essential_subject" },
{ "categoryName":"Rendering Service to the Lord", "href":"/wiki/Rendering_Service_to_the_Lord_-_an_essential_subject" },
{ "categoryName":"Renounced Order of Life", "href":"/wiki/Renounced_Order_of_Life_-_an_essential_subject" },
{ "categoryName":"Renunciation", "href":"/wiki/Renunciation_-_an_essential_subject" },
{ "categoryName":"Repentance", "href":"/wiki/Repentance_-_an_essential_subject" },
{ "categoryName":"Repetition of Birth and Death", "href":"/wiki/Repetition_of_Birth_and_Death_-_an_essential_subject" },
{ "categoryName":"Representative of God", "href":"/wiki/Representative_of_God_-_an_essential_subject" },
{ "categoryName":"Responsibility", "href":"/wiki/Responsibility_-_an_essential_subject" },
{ "categoryName":"Return Home Back to Godhead", "href":"/wiki/Return_Home_Back_to_Godhead_-_an_essential_subject" },
{ "categoryName":"Reveal", "href":"/wiki/Reveal_-_an_essential_subject" },
{ "categoryName":"Revealed Scriptures", "href":"/wiki/Revealed_Scriptures_-_an_essential_subject" },
{ "categoryName":"Revelation", "href":"/wiki/Revelation_-_an_essential_subject" },
{ "categoryName":"Rewards", "href":"/wiki/Rewards_-_an_essential_subject" },
{ "categoryName":"Rising Early in the Morning", "href":"/wiki/Rising_Early_in_the_Morning_-_an_essential_subject" },
{ "categoryName":"Rogues and Thieves", "href":"/wiki/Rogues_and_Thieves_-_an_essential_subject" },
{ "categoryName":"Root Cause", "href":"/wiki/Root_Cause_-_an_essential_subject" },
{ "categoryName":"Rules and Regulations", "href":"/wiki/Rules_and_Regulations_-_an_essential_subject" },
{ "categoryName":"Sacred Thread", "href":"/wiki/Sacred_Thread_-_an_essential_subject" },
{ "categoryName":"Sadhana-bhakti", "href":"/wiki/Sadhana-bhakti_-_an_essential_subject" },
{ "categoryName":"Sadhu", "href":"/wiki/Sadhu_-_an_essential_subject" },
{ "categoryName":"Sadhu-sanga", "href":"/wiki/Sadhu-sanga_-_an_essential_subject" },
{ "categoryName":"Sahajiyas", "href":"/wiki/Sahajiyas_-_an_essential_subject" },
{ "categoryName":"Saintly Persons", "href":"/wiki/Saintly_Persons_-_an_essential_subject" },
{ "categoryName":"Saktyavesa-avataras", "href":"/wiki/Saktyavesa-avataras_-_an_essential_subject" },
{ "categoryName":"Salvation", "href":"/wiki/Salvation_-_an_essential_subject" },
{ "categoryName":"Samadhi", "href":"/wiki/Samadhi_-_an_essential_subject" },
{ "categoryName":"Sampradaya", "href":"/wiki/Sampradaya_-_an_essential_subject" },
{ "categoryName":"Sanatana", "href":"/wiki/Sanatana_-_an_essential_subject" },
{ "categoryName":"Sanatana-dharma", "href":"/wiki/Sanatana-dharma_-_an_essential_subject" },
{ "categoryName":"Sanctify", "href":"/wiki/Sanctify_-_an_essential_subject" },
{ "categoryName":"Sankhya Philosophy", "href":"/wiki/Sankhya_Philosophy_-_an_essential_subject" },
{ "categoryName":"Sankirtana", "href":"/wiki/Sankirtana_-_an_essential_subject" },
{ "categoryName":"Sankirtana Movement", "href":"/wiki/Sankirtana_Movement_-_an_essential_subject" },
{ "categoryName":"Sannyasa", "href":"/wiki/Sannyasa_-_an_essential_subject" },
{ "categoryName":"Sastra", "href":"/wiki/Sastra_-_an_essential_subject" },
{ "categoryName":"Satisfying Krishna", "href":"/wiki/Satisfying_Krishna_-_an_essential_subject" },
{ "categoryName":"Satisfying Our Senses", "href":"/wiki/Satisfying_Our_Senses_-_an_essential_subject" },
{ "categoryName":"Sattva-guna", "href":"/wiki/Sattva-guna_-_an_essential_subject" },
{ "categoryName":"Satyaloka", "href":"/wiki/Satyaloka_-_an_essential_subject" },
{ "categoryName":"Scholarship", "href":"/wiki/Scholarship_-_an_essential_subject" },
{ "categoryName":"Science of God", "href":"/wiki/Science_of_God_-_an_essential_subject" },
{ "categoryName":"Scripture", "href":"/wiki/Scripture_-_an_essential_subject" },
{ "categoryName":"Searching after God", "href":"/wiki/Searching_after_God_-_an_essential_subject" },
{ "categoryName":"Secret", "href":"/wiki/Secret_-_an_essential_subject" },
{ "categoryName":"Secret of Success", "href":"/wiki/Secret_of_Success_-_an_essential_subject" },
{ "categoryName":"Seeing God", "href":"/wiki/Seeing_God_-_an_essential_subject" },
{ "categoryName":"Seeing God Face to Face", "href":"/wiki/Seeing_God_Face_to_Face_-_an_essential_subject" },
{ "categoryName":"Seeing Krishna", "href":"/wiki/Seeing_Krishna_-_an_essential_subject" },
{ "categoryName":"Self-realization", "href":"/wiki/Self-realization_-_an_essential_subject" },
{ "categoryName":"Self-realized Souls", "href":"/wiki/Self-realized_Souls_-_an_essential_subject" },
{ "categoryName":"Self-sufficient", "href":"/wiki/Self-sufficient_-_an_essential_subject" },
{ "categoryName":"Sense Enjoyment", "href":"/wiki/Sense_Enjoyment_-_an_essential_subject" },
{ "categoryName":"Sense Gratification", "href":"/wiki/Sense_Gratification_-_an_essential_subject" },
{ "categoryName":"Sense Objects", "href":"/wiki/Sense_Objects_-_an_essential_subject" },
{ "categoryName":"Sense Organs", "href":"/wiki/Sense_Organs_-_an_essential_subject" },
{ "categoryName":"Sense Perception", "href":"/wiki/Sense_Perception_-_an_essential_subject" },
{ "categoryName":"Sense Pleasures", "href":"/wiki/Sense_Pleasures_-_an_essential_subject" },
{ "categoryName":"Sentiments", "href":"/wiki/Sentiments_-_an_essential_subject" },
{ "categoryName":"Servant of God", "href":"/wiki/Servant_of_God_-_an_essential_subject" },
{ "categoryName":"Servant of Krishna", "href":"/wiki/Servant_of_Krishna_-_an_essential_subject" },
{ "categoryName":"Service Attitude", "href":"/wiki/Service_Attitude_-_an_essential_subject" },
{ "categoryName":"Service to Humanity", "href":"/wiki/Service_to_Humanity_-_an_essential_subject" },
{ "categoryName":"Serving Krishna", "href":"/wiki/Serving_Krishna_-_an_essential_subject" },
{ "categoryName":"Servitude", "href":"/wiki/Servitude_-_an_essential_subject" },
{ "categoryName":"Seva", "href":"/wiki/Seva_-_an_essential_subject" },
{ "categoryName":"Severe Penances", "href":"/wiki/Severe_Penances_-_an_essential_subject" },
{ "categoryName":"Sex Desire", "href":"/wiki/Sex_Desire_-_an_essential_subject" },
{ "categoryName":"Sex Enjoyment", "href":"/wiki/Sex_Enjoyment_-_an_essential_subject" },
{ "categoryName":"Sex Indulgence", "href":"/wiki/Sex_Indulgence_-_an_essential_subject" },
{ "categoryName":"Shelter of Krishna", "href":"/wiki/Shelter_of_Krishna_-_an_essential_subject" },
{ "categoryName":"Shyness", "href":"/wiki/Shyness_-_an_essential_subject" },
{ "categoryName":"Silence", "href":"/wiki/Silence_-_an_essential_subject" },
{ "categoryName":"Simplicity", "href":"/wiki/Simplicity_-_an_essential_subject" },
{ "categoryName":"Simultaneously One and Different", "href":"/wiki/Simultaneously_One_and_Different_-_an_essential_subject" },
{ "categoryName":"Sin", "href":"/wiki/Sin_-_an_essential_subject" },
{ "categoryName":"Sincere Devotees", "href":"/wiki/Sincere_Devotees_-_an_essential_subject" },
{ "categoryName":"Sincerity", "href":"/wiki/Sincerity_-_an_essential_subject" },
{ "categoryName":"Sinful Activities", "href":"/wiki/Sinful_Activities_-_an_essential_subject" },
{ "categoryName":"Sinful Life", "href":"/wiki/Sinful_Life_-_an_essential_subject" },
{ "categoryName":"Sinful Men", "href":"/wiki/Sinful_Men_-_an_essential_subject" },
{ "categoryName":"Sinful Persons", "href":"/wiki/Sinful_Persons_-_an_essential_subject" },
{ "categoryName":"Sinful Reactions", "href":"/wiki/Sinful_Reactions_-_an_essential_subject" },
{ "categoryName":"Sinner", "href":"/wiki/Sinner_-_an_essential_subject" },
{ "categoryName":"Slaughterhouse", "href":"/wiki/Slaughterhouse_-_an_essential_subject" },
{ "categoryName":"So-called Devotees", "href":"/wiki/So-called_Devotees_-_an_essential_subject" },
{ "categoryName":"So-called Education", "href":"/wiki/So-called_Education_-_an_essential_subject" },
{ "categoryName":"So-called Happiness", "href":"/wiki/So-called_Happiness_-_an_essential_subject" },
{ "categoryName":"So-called Scholars", "href":"/wiki/So-called_Scholars_-_an_essential_subject" },
{ "categoryName":"So-called Scientists", "href":"/wiki/So-called_Scientists_-_an_essential_subject" },
{ "categoryName":"Society, Friendship and Love", "href":"/wiki/Society,_Friendship_and_Love_-_an_essential_subject" },
{ "categoryName":"Solving all Economical Problems", "href":"/wiki/Solving_all_Economical_Problems_-_an_essential_subject" },
{ "categoryName":"Solving Problems", "href":"/wiki/Solving_Problems_-_an_essential_subject" },
{ "categoryName":"Solving The Problems Of Life", "href":"/wiki/Solving_The_Problems_Of_Life_-_an_essential_subject" },
{ "categoryName":"Sons of God", "href":"/wiki/Sons_of_God_-_an_essential_subject" },
{ "categoryName":"Soul within the Body", "href":"/wiki/Soul_within_the_Body_-_an_essential_subject" },
{ "categoryName":"Source of Everything", "href":"/wiki/Source_of_Everything_-_an_essential_subject" },
{ "categoryName":"Speculative Knowledge", "href":"/wiki/Speculative_Knowledge_-_an_essential_subject" },
{ "categoryName":"Spiritual Activities", "href":"/wiki/Spiritual_Activities_-_an_essential_subject" },
{ "categoryName":"Spiritual Advancement", "href":"/wiki/Spiritual_Advancement_-_an_essential_subject" },
{ "categoryName":"Spiritual Benefits", "href":"/wiki/Spiritual_Benefits_-_an_essential_subject" },
{ "categoryName":"Spiritual Bliss", "href":"/wiki/Spiritual_Bliss_-_an_essential_subject" },
{ "categoryName":"Spiritual Body", "href":"/wiki/Spiritual_Body_-_an_essential_subject" },
{ "categoryName":"Spiritual Consciousness", "href":"/wiki/Spiritual_Consciousness_-_an_essential_subject" },
{ "categoryName":"Spiritual Culture", "href":"/wiki/Spiritual_Culture_-_an_essential_subject" },
{ "categoryName":"Spiritual Education", "href":"/wiki/Spiritual_Education_-_an_essential_subject" },
{ "categoryName":"Spiritual Energy", "href":"/wiki/Spiritual_Energy_-_an_essential_subject" },
{ "categoryName":"Spiritual Existence", "href":"/wiki/Spiritual_Existence_-_an_essential_subject" },
{ "categoryName":"Spiritual Form", "href":"/wiki/Spiritual_Form_-_an_essential_subject" },
{ "categoryName":"Spiritual Happiness", "href":"/wiki/Spiritual_Happiness_-_an_essential_subject" },
{ "categoryName":"Spiritual Identity", "href":"/wiki/Spiritual_Identity_-_an_essential_subject" },
{ "categoryName":"Spiritual Kingdom", "href":"/wiki/Spiritual_Kingdom_-_an_essential_subject" },
{ "categoryName":"Spiritual Knowledge", "href":"/wiki/Spiritual_Knowledge_-_an_essential_subject" },
{ "categoryName":"Spiritual Life", "href":"/wiki/Spiritual_Life_-_an_essential_subject" },
{ "categoryName":"Spiritual Master", "href":"/wiki/Spiritual_Master_-_an_essential_subject" },
{ "categoryName":"Spiritual Nature", "href":"/wiki/Spiritual_Nature_-_an_essential_subject" },
{ "categoryName":"Spiritual Perfection", "href":"/wiki/Spiritual_Perfection_-_an_essential_subject" },
{ "categoryName":"Spiritual Planets", "href":"/wiki/Spiritual_Planets_-_an_essential_subject" },
{ "categoryName":"Spiritual Position", "href":"/wiki/Spiritual_Position_-_an_essential_subject" },
{ "categoryName":"Spiritual Potency", "href":"/wiki/Spiritual_Potency_-_an_essential_subject" },
{ "categoryName":"Spiritual Progress", "href":"/wiki/Spiritual_Progress_-_an_essential_subject" },
{ "categoryName":"Spiritual Realization", "href":"/wiki/Spiritual_Realization_-_an_essential_subject" },
{ "categoryName":"Spiritual Science", "href":"/wiki/Spiritual_Science_-_an_essential_subject" },
{ "categoryName":"Spiritual Sky", "href":"/wiki/Spiritual_Sky_-_an_essential_subject" },
{ "categoryName":"Spiritual Spark", "href":"/wiki/Spiritual_Spark_-_an_essential_subject" },
{ "categoryName":"Spiritual Understanding", "href":"/wiki/Spiritual_Understanding_-_an_essential_subject" },
{ "categoryName":"Spiritual World", "href":"/wiki/Spiritual_World_-_an_essential_subject" },
{ "categoryName":"Spiritualists", "href":"/wiki/Spiritualists_-_an_essential_subject" },
{ "categoryName":"Spiritually Advanced", "href":"/wiki/Spiritually_Advanced_-_an_essential_subject" },
{ "categoryName":"Spontaneous Love", "href":"/wiki/Spontaneous_Love_-_an_essential_subject" },
{ "categoryName":"Spreading Krishna Consciousness", "href":"/wiki/Spreading_Krishna_Consciousness_-_an_essential_subject" },
{ "categoryName":"Spreading the Krishna Consciousness Movement", "href":"/wiki/Spreading_the_Krishna_Consciousness_Movement_-_an_essential_subject" },
{ "categoryName":"Sraddha", "href":"/wiki/Sraddha_-_an_essential_subject" },
{ "categoryName":"Sravana", "href":"/wiki/Sravana_-_an_essential_subject" },
{ "categoryName":"Sruti", "href":"/wiki/Sruti_-_an_essential_subject" },
{ "categoryName":"Stages of Devotional Service", "href":"/wiki/Stages_of_Devotional_Service_-_an_essential_subject" },
{ "categoryName":"Starting the Krishna Consciousness Movement", "href":"/wiki/Starting_the_Krishna_Consciousness_Movement_-_an_essential_subject" },
{ "categoryName":"Starvation", "href":"/wiki/Starvation_-_an_essential_subject" },
{ "categoryName":"Stopping Death", "href":"/wiki/Stopping_Death_-_an_essential_subject" },
{ "categoryName":"Stringent Laws of Material Nature", "href":"/wiki/Stringent_Laws_of_Material_Nature_-_an_essential_subject" },
{ "categoryName":"Struggle for Existence", "href":"/wiki/Struggle_for_Existence_-_an_essential_subject" },
{ "categoryName":"Submission", "href":"/wiki/Submission_-_an_essential_subject" },
{ "categoryName":"Subtle Body", "href":"/wiki/Subtle_Body_-_an_essential_subject" },
{ "categoryName":"Success", "href":"/wiki/Success_-_an_essential_subject" },
{ "categoryName":"Successful Life", "href":"/wiki/Successful_Life_-_an_essential_subject" },
{ "categoryName":"Suffering", "href":"/wiki/Suffering_-_an_essential_subject" },
{ "categoryName":"Suicide", "href":"/wiki/Suicide_-_an_essential_subject" },
{ "categoryName":"Supersoul", "href":"/wiki/Supersoul_-_an_essential_subject" },
{ "categoryName":"Supreme Absolute Truth", "href":"/wiki/Supreme_Absolute_Truth_-_an_essential_subject" },
{ "categoryName":"Supreme Consciousness", "href":"/wiki/Supreme_Consciousness_-_an_essential_subject" },
{ "categoryName":"Supreme Controller", "href":"/wiki/Supreme_Controller_-_an_essential_subject" },
{ "categoryName":"Supreme Enjoyer", "href":"/wiki/Supreme_Enjoyer_-_an_essential_subject" },
{ "categoryName":"Supreme Father", "href":"/wiki/Supreme_Father_-_an_essential_subject" },
{ "categoryName":"Supreme Friend", "href":"/wiki/Supreme_Friend_-_an_essential_subject" },
{ "categoryName":"Supreme Goal", "href":"/wiki/Supreme_Goal_-_an_essential_subject" },
{ "categoryName":"Supreme Person", "href":"/wiki/Supreme_Person_-_an_essential_subject" },
{ "categoryName":"Supreme Personality of Godhead", "href":"/wiki/Supreme_Personality_of_Godhead_-_an_essential_subject" },
{ "categoryName":"Supreme Source", "href":"/wiki/Supreme_Source_-_an_essential_subject" },
{ "categoryName":"Supreme Spirit", "href":"/wiki/Supreme_Spirit_-_an_essential_subject" },
{ "categoryName":"Supreme Truth", "href":"/wiki/Supreme_Truth_-_an_essential_subject" },
{ "categoryName":"Surrender", "href":"/wiki/Surrender_-_an_essential_subject" },
{ "categoryName":"Surrender to Krishna", "href":"/wiki/Surrender_to_Krishna_-_an_essential_subject" },
{ "categoryName":"Surrendered Souls", "href":"/wiki/Surrendered_Souls_-_an_essential_subject" },
{ "categoryName":"Sympathetic", "href":"/wiki/Sympathetic_-_an_essential_subject" },
{ "categoryName":"Sympathy", "href":"/wiki/Sympathy_-_an_essential_subject" },
{ "categoryName":"Taking Birth", "href":"/wiki/Taking_Birth_-_an_essential_subject" },
{ "categoryName":"Taking Sannyasa", "href":"/wiki/Taking_Sannyasa_-_an_essential_subject" },
{ "categoryName":"Taking Shelter", "href":"/wiki/Taking_Shelter_-_an_essential_subject" },
{ "categoryName":"Taking to Devotional Service", "href":"/wiki/Taking_to_Devotional_Service_-_an_essential_subject" },
{ "categoryName":"Talking Nonsense", "href":"/wiki/Talking_Nonsense_-_an_essential_subject" },
{ "categoryName":"Tamo-guna", "href":"/wiki/Tamo-guna_-_an_essential_subject" },
{ "categoryName":"Tapasya", "href":"/wiki/Tapasya_-_an_essential_subject" },
{ "categoryName":"Tattva", "href":"/wiki/Tattva_-_an_essential_subject" },
{ "categoryName":"Temple Worship", "href":"/wiki/Temple_Worship_-_an_essential_subject" },
{ "categoryName":"Tests", "href":"/wiki/Tests_-_an_essential_subject" },
{ "categoryName":"The Holy Names of God Give Liberation", "href":"/wiki/The_Holy_Names_of_God_Give_Liberation_-_an_essential_subject" },
{ "categoryName":"The Time Will Come", "href":"/wiki/The_Time_Will_Come_-_an_essential_subject" },
{ "categoryName":"Theism", "href":"/wiki/Theism_-_an_essential_subject" },
{ "categoryName":"Theoretical Knowledge", "href":"/wiki/Theoretical_Knowledge_-_an_essential_subject" },
{ "categoryName":"There is No God", "href":"/wiki/There_is_No_God_-_an_essential_subject" },
{ "categoryName":"Thinking of Krishna", "href":"/wiki/Thinking_of_Krishna_-_an_essential_subject" },
{ "categoryName":"Three Modes of Material Nature", "href":"/wiki/Three_Modes_of_Material_Nature_-_an_essential_subject" },
{ "categoryName":"Tilaka", "href":"/wiki/Tilaka_-_an_essential_subject" },
{ "categoryName":"Time Factor", "href":"/wiki/Time_Factor_-_an_essential_subject" },
{ "categoryName":"Time Immemorial", "href":"/wiki/Time_Immemorial_-_an_essential_subject" },
{ "categoryName":"Time, Place and Circumstances", "href":"/wiki/Time,_Place_and_Circumstances_-_an_essential_subject" },
{ "categoryName":"Tolerance", "href":"/wiki/Tolerance_-_an_essential_subject" },
{ "categoryName":"Tradition", "href":"/wiki/Tradition_-_an_essential_subject" },
{ "categoryName":"Transcendence", "href":"/wiki/Transcendence_-_an_essential_subject" },
{ "categoryName":"Transcendental Activities", "href":"/wiki/Transcendental_Activities_-_an_essential_subject" },
{ "categoryName":"Transcendental Bliss", "href":"/wiki/Transcendental_Bliss_-_an_essential_subject" },
{ "categoryName":"Transcendental Body", "href":"/wiki/Transcendental_Body_-_an_essential_subject" },
{ "categoryName":"Transcendental Devotional Service", "href":"/wiki/Transcendental_Devotional_Service_-_an_essential_subject" },
{ "categoryName":"Transcendental Form", "href":"/wiki/Transcendental_Form_-_an_essential_subject" },
{ "categoryName":"Transcendental Knowledge", "href":"/wiki/Transcendental_Knowledge_-_an_essential_subject" },
{ "categoryName":"Transcendental Life", "href":"/wiki/Transcendental_Life_-_an_essential_subject" },
{ "categoryName":"Transcendental Literature", "href":"/wiki/Transcendental_Literature_-_an_essential_subject" },
{ "categoryName":"Transcendental Love", "href":"/wiki/Transcendental_Love_-_an_essential_subject" },
{ "categoryName":"Transcendental Loving Service", "href":"/wiki/Transcendental_Loving_Service_-_an_essential_subject" },
{ "categoryName":"Transcendental Loving Service of the Lord", "href":"/wiki/Transcendental_Loving_Service_of_the_Lord_-_an_essential_subject" },
{ "categoryName":"Transcendental Mellows", "href":"/wiki/Transcendental_Mellows_-_an_essential_subject" },
{ "categoryName":"Transcendental Nature of the Lord", "href":"/wiki/Transcendental_Nature_of_the_Lord_-_an_essential_subject" },
{ "categoryName":"Transcendental Position", "href":"/wiki/Transcendental_Position_-_an_essential_subject" },
{ "categoryName":"Transcendental Qualities", "href":"/wiki/Transcendental_Qualities_-_an_essential_subject" },
{ "categoryName":"Transcendental Science", "href":"/wiki/Transcendental_Science_-_an_essential_subject" },
{ "categoryName":"Transcendental Service of the Lord", "href":"/wiki/Transcendental_Service_of_the_Lord_-_an_essential_subject" },
{ "categoryName":"Transcendental Subject Matter", "href":"/wiki/Transcendental_Subject_Matter_-_an_essential_subject" },
{ "categoryName":"Transferring to the Spiritual World", "href":"/wiki/Transferring_to_the_Spiritual_World_-_an_essential_subject" },
{ "categoryName":"Transformation", "href":"/wiki/Transformation_-_an_essential_subject" },
{ "categoryName":"Transmigrating From One Body To Another", "href":"/wiki/Transmigrating_From_One_Body_To_Another_-_an_essential_subject" },
{ "categoryName":"Transmigration of the Soul", "href":"/wiki/Transmigration_of_the_Soul_-_an_essential_subject" },
{ "categoryName":"Tribulations", "href":"/wiki/Tribulations_-_an_essential_subject" },
{ "categoryName":"Trust", "href":"/wiki/Trust_-_an_essential_subject" },
{ "categoryName":"Trust in God", "href":"/wiki/Trust_in_God_-_an_essential_subject" },
{ "categoryName":"Truth", "href":"/wiki/Truth_-_an_essential_subject" },
{ "categoryName":"Truthfulness", "href":"/wiki/Truthfulness_-_an_essential_subject" },
{ "categoryName":"Tulasi", "href":"/wiki/Tulasi_-_an_essential_subject" },
{ "categoryName":"Ugra-karma", "href":"/wiki/Ugra-karma_-_an_essential_subject" },
{ "categoryName":"Ultimate Destination", "href":"/wiki/Ultimate_Destination_-_an_essential_subject" },
{ "categoryName":"Ultimate Goal of Life", "href":"/wiki/Ultimate_Goal_of_Life_-_an_essential_subject" },
{ "categoryName":"Unalloyed Devotees", "href":"/wiki/Unalloyed_Devotees_-_an_essential_subject" },
{ "categoryName":"Unalloyed Devotional Service", "href":"/wiki/Unalloyed_Devotional_Service_-_an_essential_subject" },
{ "categoryName":"Unchasity", "href":"/wiki/Unchasity_-_an_essential_subject" },
{ "categoryName":"Uncivilized", "href":"/wiki/Uncivilized_-_an_essential_subject" },
{ "categoryName":"Unconscious", "href":"/wiki/Unconscious_-_an_essential_subject" },
{ "categoryName":"Uncontaminated", "href":"/wiki/Uncontaminated_-_an_essential_subject" },
{ "categoryName":"Under The Direction of Krishna", "href":"/wiki/Under_The_Direction_of_Krishna_-_an_essential_subject" },
{ "categoryName":"Understanding Bhagavad-gita", "href":"/wiki/Understanding_Bhagavad-gita_-_an_essential_subject" },
{ "categoryName":"Understanding God", "href":"/wiki/Understanding_God_-_an_essential_subject" },
{ "categoryName":"Understanding Krishna", "href":"/wiki/Understanding_Krishna_-_an_essential_subject" },
{ "categoryName":"Understanding Srimad-Bhagavatam", "href":"/wiki/Understanding_Srimad-Bhagavatam_-_an_essential_subject" },
{ "categoryName":"Understanding the Absolute Truth", "href":"/wiki/Understanding_the_Absolute_Truth_-_an_essential_subject" },
{ "categoryName":"Understanding the Krishna Consciousness Movement", "href":"/wiki/Understanding_the_Krishna_Consciousness_Movement_-_an_essential_subject" },
{ "categoryName":"Undesirable", "href":"/wiki/Undesirable_-_an_essential_subject" },
{ "categoryName":"Undisturbed", "href":"/wiki/Undisturbed_-_an_essential_subject" },
{ "categoryName":"Unfortunate", "href":"/wiki/Unfortunate_-_an_essential_subject" },
{ "categoryName":"Unhappy", "href":"/wiki/Unhappy_-_an_essential_subject" },
{ "categoryName":"Unintelligent", "href":"/wiki/Unintelligent_-_an_essential_subject" },
{ "categoryName":"Unsuccessful", "href":"/wiki/Unsuccessful_-_an_essential_subject" },
{ "categoryName":"Untruth", "href":"/wiki/Untruth_-_an_essential_subject" },
{ "categoryName":"Unwanted Things", "href":"/wiki/Unwanted_Things_-_an_essential_subject" },
{ "categoryName":"Useless Waste of Time", "href":"/wiki/Useless_Waste_of_Time_-_an_essential_subject" },
{ "categoryName":"Vaikuntha", "href":"/wiki/Vaikuntha_-_an_essential_subject" },
{ "categoryName":"Vairagya", "href":"/wiki/Vairagya_-_an_essential_subject" },
{ "categoryName":"Vaisnava", "href":"/wiki/Vaisnava_-_an_essential_subject" },
{ "categoryName":"Vaisnava Philosophy", "href":"/wiki/Vaisnava_Philosophy_-_an_essential_subject" },
{ "categoryName":"Vanaprastha", "href":"/wiki/Vanaprastha_-_an_essential_subject" },
{ "categoryName":"Vani", "href":"/wiki/Vani_-_an_essential_subject" },
{ "categoryName":"Vapu", "href":"/wiki/Vapu_-_an_essential_subject" },
{ "categoryName":"Varnasrama", "href":"/wiki/Varnasrama_-_an_essential_subject" },
{ "categoryName":"Varnasrama-dharma", "href":"/wiki/Varnasrama-dharma_-_an_essential_subject" },
{ "categoryName":"Vedanta Philosophy", "href":"/wiki/Vedanta_Philosophy_-_an_essential_subject" },
{ "categoryName":"Vedas", "href":"/wiki/Vedas_-_an_essential_subject" },
{ "categoryName":"Vedic Civilization", "href":"/wiki/Vedic_Civilization_-_an_essential_subject" },
{ "categoryName":"Vedic Culture", "href":"/wiki/Vedic_Culture_-_an_essential_subject" },
{ "categoryName":"Vedic Evidence", "href":"/wiki/Vedic_Evidence_-_an_essential_subject" },
{ "categoryName":"Vedic Hymns", "href":"/wiki/Vedic_Hymns_-_an_essential_subject" },
{ "categoryName":"Vedic Injunctions", "href":"/wiki/Vedic_Injunctions_-_an_essential_subject" },
{ "categoryName":"Vedic Instructions", "href":"/wiki/Vedic_Instructions_-_an_essential_subject" },
{ "categoryName":"Vedic Knowledge", "href":"/wiki/Vedic_Knowledge_-_an_essential_subject" },
{ "categoryName":"Vedic Literature", "href":"/wiki/Vedic_Literature_-_an_essential_subject" },
{ "categoryName":"Vedic Mantras", "href":"/wiki/Vedic_Mantras_-_an_essential_subject" },
{ "categoryName":"Vedic Principles", "href":"/wiki/Vedic_Principles_-_an_essential_subject" },
{ "categoryName":"Vedic Rituals", "href":"/wiki/Vedic_Rituals_-_an_essential_subject" },
{ "categoryName":"Vedic Scriptures", "href":"/wiki/Vedic_Scriptures_-_an_essential_subject" },
{ "categoryName":"Vedic Society", "href":"/wiki/Vedic_Society_-_an_essential_subject" },
{ "categoryName":"Vedic Version", "href":"/wiki/Vedic_Version_-_an_essential_subject" },
{ "categoryName":"Vedic Wisdom", "href":"/wiki/Vedic_Wisdom_-_an_essential_subject" },
{ "categoryName":"Vegetarian", "href":"/wiki/Vegetarian_-_an_essential_subject" },
{ "categoryName":"Very Expert", "href":"/wiki/Very_Expert_-_an_essential_subject" },
{ "categoryName":"Very Happy", "href":"/wiki/Very_Happy_-_an_essential_subject" },
{ "categoryName":"Very Intelligent", "href":"/wiki/Very_Intelligent_-_an_essential_subject" },
{ "categoryName":"Very Sincere", "href":"/wiki/Very_Sincere_-_an_essential_subject" },
{ "categoryName":"Vijnana", "href":"/wiki/Vijnana_-_an_essential_subject" },
{ "categoryName":"Vikarma", "href":"/wiki/Vikarma_-_an_essential_subject" },
{ "categoryName":"Visnu-tattva", "href":"/wiki/Visnu-tattva_-_an_essential_subject" },
{ "categoryName":"Vital Force", "href":"/wiki/Vital_Force_-_an_essential_subject" },
{ "categoryName":"Vrndavana", "href":"/wiki/Vrndavana_-_an_essential_subject" },
{ "categoryName":"War", "href":"/wiki/War_-_an_essential_subject" },
{ "categoryName":"War and Sinful Activities", "href":"/wiki/War_and_Sinful_Activities_-_an_essential_subject" },
{ "categoryName":"Wasting Time", "href":"/wiki/Wasting_Time_-_an_essential_subject" },
{ "categoryName":"Water of the Ganges", "href":"/wiki/Water_of_the_Ganges_-_an_essential_subject" },
{ "categoryName":"Welfare Activities", "href":"/wiki/Welfare_Activities_-_an_essential_subject" },
{ "categoryName":"Western Civilization", "href":"/wiki/Western_Civilization_-_an_essential_subject" },
{ "categoryName":"Western World", "href":"/wiki/Western_World_-_an_essential_subject" },
{ "categoryName":"What is Bhagavad-gita", "href":"/wiki/What_is_Bhagavad-gita_-_an_essential_subject" },
{ "categoryName":"What is Education", "href":"/wiki/What_is_Education_-_an_essential_subject" },
{ "categoryName":"What is God", "href":"/wiki/What_is_God_-_an_essential_subject" },
{ "categoryName":"What is Srimad-Bhagavatam", "href":"/wiki/What_is_Srimad-Bhagavatam_-_an_essential_subject" },
{ "categoryName":"Whole Human Society", "href":"/wiki/Whole_Human_Society_-_an_essential_subject" },
{ "categoryName":"Will of the Lord", "href":"/wiki/Will_of_the_Lord_-_an_essential_subject" },
{ "categoryName":"Wisdom", "href":"/wiki/Wisdom_-_an_essential_subject" },
{ "categoryName":"Within the Heart", "href":"/wiki/Within_the_Heart_-_an_essential_subject" },
{ "categoryName":"Without Any Doubt", "href":"/wiki/Without_Any_Doubt_-_an_essential_subject" },
{ "categoryName":"Without Deviation", "href":"/wiki/Without_Deviation_-_an_essential_subject" },
{ "categoryName":"Without Hesitation", "href":"/wiki/Without_Hesitation_-_an_essential_subject" },
{ "categoryName":"Without Knowledge", "href":"/wiki/Without_Knowledge_-_an_essential_subject" },
{ "categoryName":"Without Krishna Consciousness", "href":"/wiki/Without_Krishna_Consciousness_-_an_essential_subject" },
{ "categoryName":"Words of Krishna", "href":"/wiki/Words_of_Krishna_-_an_essential_subject" },
{ "categoryName":"Working for Krishna", "href":"/wiki/Working_for_Krishna_-_an_essential_subject" },
{ "categoryName":"Worshiping", "href":"/wiki/Worshiping_-_an_essential_subject" },
{ "categoryName":"Worshiping God", "href":"/wiki/Worshiping_God_-_an_essential_subject" },
{ "categoryName":"Worshiping Krishna", "href":"/wiki/Worshiping_Krishna_-_an_essential_subject" },
{ "categoryName":"Worshiping Lord Vishnu", "href":"/wiki/Worshiping_Lord_Vishnu_-_an_essential_subject" },
{ "categoryName":"Worshiping the Supreme Personality of Godhead", "href":"/wiki/Worshiping_the_Supreme_Personality_of_Godhead_-_an_essential_subject" },
{ "categoryName":"Yajna", "href":"/wiki/Yajna_-_an_essential_subject" },
{ "categoryName":"Yamuna River", "href":"/wiki/Yamuna_River_-_an_essential_subject" },
{ "categoryName":"Yoga", "href":"/wiki/Yoga_-_an_essential_subject" },
{ "categoryName":"Yoga Practice", "href":"/wiki/Yoga_Practice_-_an_essential_subject" },
{ "categoryName":"Yoga System", "href":"/wiki/Yoga_System_-_an_essential_subject" },
{ "categoryName":"Yogamaya", "href":"/wiki/Yogamaya_-_an_essential_subject" },
{ "categoryName":"Yogi", "href":"/wiki/Yogi_-_an_essential_subject" },
{ "categoryName":"Yukta-vairagya", "href":"/wiki/Yukta-vairagya_-_an_essential_subject" }
]
module.exports = data